// Every piece of app text, in English, Hindi, Bengali and Punjabi (SRS D-M11, NF-10).
// The Hindi, Bengali and Punjabi text must be checked by a native speaker of each before a store
// release (SRS section 13, "Done means"). {name}-style holes are filled by t().

const en = {
  appName: "TatvaOS School",
  tagline: "One app for your whole school",
  byTechvein: "by Techvein",
  language: "English",
  chooseLanguage: "Choose language",

  welcomeTitle: "Everything about school, in one app",
  welcomeSub: "For students, parents and teachers.",
  getStarted: "Get started",
  haveCode: "I have a school code",
  previewPresent: "Present today",
  previewMarked: "Marked 8:42 am",
  previewFees: "Fees paid",
  previewReceipt: "Receipt ready",
  previewPtm: "PTM Saturday",
  previewNotice: "New notice",

  findSchool: "Find your school",
  findSchoolSub: "You only do this once. We remember it on this phone.",
  searchPlaceholder: "School name or city",
  schoolCode: "School code",
  scanQr: "Scan QR",
  typeThree: "Type at least 3 letters of your school name or city",
  searchResults: "RESULTS",
  noSchool: "No school found. Try the school code from your school.",
  continue: "Continue",
  enterCode: "Enter your school code",
  codePlaceholder: "e.g. DEMO",
  codeHelp: "The code is on the school's notice or QR poster.",
  check: "Check",
  cancel: "Cancel",

  changeSchool: "Change school",
  signIn: "Sign in",
  usernameLabel: "Username or admission no.",
  usernamePlaceholder: "e.g. DPS2026-0412",
  passwordLabel: "Password",
  keepSignedIn: "Keep me signed in",
  forgot: "Forgot?",
  parentsHint: "Parents: use your child's student login.",
  twoChildrenHint: "Two children? Add the second one after signing in.",
  fillBoth: "Enter your username and password.",
  triesLeft: "{n} tries left before sign-in is locked for 15 minutes.",
  forgotSoon: "Forgot password with OTP comes in the next build. Until then, please ask the school office.",
  showPassword: "Show password",
  hidePassword: "Hide password",

  staffSoon: "The teacher and staff screens come in Phase 2. Please use the TatvaOS website for now.",
  notEnabled: "{school} has not switched on the app yet. Please use the TatvaOS website for now.",
  updateTitle: "Please update the app",
  updateBody: "This version of TatvaOS School is too old for your school. Update it from the store to continue.",
  mustChange: "Your school gave you a temporary password. Please change it on the TatvaOS website, then sign in again.",
  signOut: "Sign out",
  retry: "Try again",

  goodMorning: "Good morning, {name}",
  goodAfternoon: "Good afternoon, {name}",
  goodEvening: "Good evening, {name}",
  presentToday: "Present",
  absentToday: "Absent",
  lateToday: "Late",
  notMarked: "Not marked",
  todayTerm: "Today · {pct}% this month",
  homework: "Homework",
  hwToday: "{n} today",
  hwNone: "None today",
  hwOne: "1 today",
  dueOn: "Due {date}",
  overdue: "Overdue",
  noDues: "No dues",
  quickAccess: "Quick access",
  attendance: "Attendance",
  fees: "Fees",
  results: "Results",
  timetable: "Timetable",
  notices: "Notices",
  library: "Library",
  comingSoon: "This screen comes in the next build.",
  notifications: "Notifications, {n} unread",
  navHome: "Home",
  navCalendar: "Calendar",
  navProfile: "Profile",
  offlineCopy: "Offline. Showing the copy from {time}.",

  attendanceTitle: "Attendance",
  present: "Present",
  late: "Late",
  absent: "Absent",
  leave: "Leave",
  holidayOff: "Holiday / off",
  days: "{n} days",
  day: "{n} day",
  prevMonth: "Previous month",
  nextMonth: "Next month",
  applyLeave: "Apply for leave",
  pending: "Pending",
  approved: "Approved",
  rejected: "Rejected",
  cancelled: "Cancelled",
  noAttendance: "No attendance marked this month yet.",

  feesTitle: "Fees",
  totalDueNow: "Total due now",
  nothingDue: "Nothing due now",
  nextDue: "Next due {date}",
  breakdown: "WHAT IS DUE",
  fine: "Fine",
  pay: "Pay {amount}",
  payComing: "Online payment comes in the next build. You can pay at the school office or on the TatvaOS website.",
  securePayment: "Secure payment · UPI, cards, net banking",
  receipts: "Receipts",
  noReceipts: "No receipts yet.",
  paidOn: "Paid {date} · {mode}",
  reverted: "Cancelled by school",
  downloadReceipt: "Download receipt",

  switchChild: "Switch child",
  switchChildSub: "Each child stays signed in with their own school login.",
  open: "Open",
  addChild: "Add a child",
  addChildSub: "Same school or a different one",
  alertsBoth: "Alerts come for every child all the time, even when another child is open.",
  signOutOf: "Sign out of {name}",

  errorGeneric: "Something went wrong. Please try again.",
  months: "January,February,March,April,May,June,July,August,September,October,November,December",
  weekdaysShort: "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
  weekdays: "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday",
};

export type StringKey = keyof typeof en;

const hi: Record<StringKey, string> = {
  appName: "TatvaOS School",
  tagline: "पूरे स्कूल के लिए एक ऐप",
  byTechvein: "Techvein द्वारा",
  language: "हिन्दी",
  chooseLanguage: "भाषा चुनें",
  welcomeTitle: "स्कूल की हर बात, एक ऐप में",
  welcomeSub: "छात्रों, अभिभावकों और शिक्षकों के लिए।",
  getStarted: "शुरू करें",
  haveCode: "मेरे पास स्कूल कोड है",
  previewPresent: "आज उपस्थित",
  previewMarked: "सुबह 8:42 बजे दर्ज",
  previewFees: "फ़ीस जमा",
  previewReceipt: "रसीद तैयार",
  previewPtm: "शनिवार को PTM",
  previewNotice: "नई सूचना",
  findSchool: "अपना स्कूल खोजें",
  findSchoolSub: "यह सिर्फ़ एक बार करना है। यह फ़ोन इसे याद रखेगा।",
  searchPlaceholder: "स्कूल का नाम या शहर",
  schoolCode: "स्कूल कोड",
  scanQr: "QR स्कैन करें",
  typeThree: "स्कूल के नाम या शहर के कम से कम 3 अक्षर लिखें",
  searchResults: "परिणाम",
  noSchool: "कोई स्कूल नहीं मिला। अपने स्कूल का कोड आज़माएँ।",
  continue: "आगे बढ़ें",
  enterCode: "अपना स्कूल कोड लिखें",
  codePlaceholder: "जैसे DEMO",
  codeHelp: "कोड स्कूल की सूचना या QR पोस्टर पर है।",
  check: "जाँचें",
  cancel: "रद्द करें",
  changeSchool: "स्कूल बदलें",
  signIn: "साइन इन",
  usernameLabel: "यूज़रनेम या प्रवेश संख्या",
  usernamePlaceholder: "जैसे DPS2026-0412",
  passwordLabel: "पासवर्ड",
  keepSignedIn: "मुझे साइन इन रखें",
  forgot: "भूल गए?",
  parentsHint: "अभिभावक: अपने बच्चे के छात्र लॉगिन का उपयोग करें।",
  twoChildrenHint: "दो बच्चे हैं? साइन इन के बाद दूसरा जोड़ें।",
  fillBoth: "अपना यूज़रनेम और पासवर्ड लिखें।",
  triesLeft: "साइन इन 15 मिनट के लिए बंद होने से पहले {n} कोशिशें बाकी हैं।",
  forgotSoon: "OTP से पासवर्ड बदलना अगले बिल्ड में आएगा। तब तक कृपया स्कूल ऑफ़िस से पूछें।",
  showPassword: "पासवर्ड दिखाएँ",
  hidePassword: "पासवर्ड छिपाएँ",
  staffSoon: "शिक्षक और स्टाफ़ की स्क्रीन फ़ेज़ 2 में आएँगी। अभी TatvaOS वेबसाइट का उपयोग करें।",
  notEnabled: "{school} ने अभी ऐप चालू नहीं किया है। अभी TatvaOS वेबसाइट का उपयोग करें।",
  updateTitle: "कृपया ऐप अपडेट करें",
  updateBody: "TatvaOS School का यह संस्करण आपके स्कूल के लिए पुराना है। आगे बढ़ने के लिए स्टोर से अपडेट करें।",
  mustChange: "स्कूल ने आपको अस्थायी पासवर्ड दिया है। इसे TatvaOS वेबसाइट पर बदलें, फिर दोबारा साइन इन करें।",
  signOut: "साइन आउट",
  retry: "फिर कोशिश करें",
  goodMorning: "सुप्रभात, {name}",
  goodAfternoon: "नमस्ते, {name}",
  goodEvening: "शुभ संध्या, {name}",
  presentToday: "उपस्थित",
  absentToday: "अनुपस्थित",
  lateToday: "देर से",
  notMarked: "दर्ज नहीं",
  todayTerm: "आज · इस महीने {pct}%",
  homework: "होमवर्क",
  hwToday: "आज {n}",
  hwNone: "आज कोई नहीं",
  hwOne: "आज 1",
  dueOn: "{date} तक देय",
  overdue: "देय तिथि निकल गई",
  noDues: "कोई बकाया नहीं",
  quickAccess: "त्वरित पहुँच",
  attendance: "उपस्थिति",
  fees: "फ़ीस",
  results: "परिणाम",
  timetable: "समय-सारणी",
  notices: "सूचनाएँ",
  library: "पुस्तकालय",
  comingSoon: "यह स्क्रीन अगले बिल्ड में आएगी।",
  notifications: "सूचनाएँ, {n} अपठित",
  navHome: "होम",
  navCalendar: "कैलेंडर",
  navProfile: "प्रोफ़ाइल",
  offlineCopy: "ऑफ़लाइन। {time} की कॉपी दिख रही है।",
  attendanceTitle: "उपस्थिति",
  present: "उपस्थित",
  late: "देर से",
  absent: "अनुपस्थित",
  leave: "छुट्टी",
  holidayOff: "अवकाश / बंद",
  days: "{n} दिन",
  day: "{n} दिन",
  prevMonth: "पिछला महीना",
  nextMonth: "अगला महीना",
  applyLeave: "छुट्टी के लिए आवेदन",
  pending: "लंबित",
  approved: "स्वीकृत",
  rejected: "अस्वीकृत",
  cancelled: "रद्द",
  noAttendance: "इस महीने अभी कोई उपस्थिति दर्ज नहीं है।",
  feesTitle: "फ़ीस",
  totalDueNow: "अभी कुल देय",
  nothingDue: "अभी कुछ देय नहीं",
  nextDue: "अगली देय तिथि {date}",
  breakdown: "क्या देय है",
  fine: "जुर्माना",
  pay: "{amount} भुगतान करें",
  payComing: "ऑनलाइन भुगतान अगले बिल्ड में आएगा। आप स्कूल ऑफ़िस या TatvaOS वेबसाइट पर भुगतान कर सकते हैं।",
  securePayment: "सुरक्षित भुगतान · UPI, कार्ड, नेट बैंकिंग",
  receipts: "रसीदें",
  noReceipts: "अभी कोई रसीद नहीं।",
  paidOn: "{date} को जमा · {mode}",
  reverted: "स्कूल द्वारा रद्द",
  downloadReceipt: "रसीद डाउनलोड करें",
  switchChild: "बच्चा बदलें",
  switchChildSub: "हर बच्चा अपने स्कूल लॉगिन से साइन इन रहता है।",
  open: "खुला",
  addChild: "बच्चा जोड़ें",
  addChildSub: "वही स्कूल या कोई दूसरा",
  alertsBoth: "हर बच्चे की सूचनाएँ हमेशा आती हैं, भले ही दूसरा बच्चा खुला हो।",
  signOutOf: "{name} से साइन आउट",
  errorGeneric: "कुछ गलत हो गया। कृपया फिर कोशिश करें।",
  months: "जनवरी,फ़रवरी,मार्च,अप्रैल,मई,जून,जुलाई,अगस्त,सितंबर,अक्टूबर,नवंबर,दिसंबर",
  weekdaysShort: "रवि,सोम,मंगल,बुध,गुरु,शुक्र,शनि",
  weekdays: "रविवार,सोमवार,मंगलवार,बुधवार,गुरुवार,शुक्रवार,शनिवार",
};

const bn: Record<StringKey, string> = {
  appName: "TatvaOS School",
  tagline: "পুরো স্কুলের জন্য একটি অ্যাপ",
  byTechvein: "Techvein-এর তৈরি",
  language: "বাংলা",
  chooseLanguage: "ভাষা বেছে নিন",
  welcomeTitle: "স্কুলের সব কিছু, একটি অ্যাপে",
  welcomeSub: "ছাত্রছাত্রী, অভিভাবক ও শিক্ষকদের জন্য।",
  getStarted: "শুরু করুন",
  haveCode: "আমার কাছে স্কুল কোড আছে",
  previewPresent: "আজ উপস্থিত",
  previewMarked: "সকাল 8:42-এ নথিভুক্ত",
  previewFees: "ফি জমা হয়েছে",
  previewReceipt: "রসিদ তৈরি",
  previewPtm: "শনিবার PTM",
  previewNotice: "নতুন নোটিস",
  findSchool: "আপনার স্কুল খুঁজুন",
  findSchoolSub: "এটা একবারই করতে হবে। এই ফোন মনে রাখবে।",
  searchPlaceholder: "স্কুলের নাম বা শহর",
  schoolCode: "স্কুল কোড",
  scanQr: "QR স্ক্যান করুন",
  typeThree: "স্কুলের নাম বা শহরের অন্তত 3টি অক্ষর লিখুন",
  searchResults: "ফলাফল",
  noSchool: "কোনো স্কুল পাওয়া যায়নি। আপনার স্কুলের কোড দিয়ে চেষ্টা করুন।",
  continue: "এগিয়ে যান",
  enterCode: "আপনার স্কুল কোড লিখুন",
  codePlaceholder: "যেমন DEMO",
  codeHelp: "কোডটি স্কুলের নোটিস বা QR পোস্টারে আছে।",
  check: "যাচাই করুন",
  cancel: "বাতিল",
  changeSchool: "স্কুল বদলান",
  signIn: "সাইন ইন",
  usernameLabel: "ইউজারনেম বা ভর্তি নম্বর",
  usernamePlaceholder: "যেমন DPS2026-0412",
  passwordLabel: "পাসওয়ার্ড",
  keepSignedIn: "আমাকে সাইন ইন রাখুন",
  forgot: "ভুলে গেছেন?",
  parentsHint: "অভিভাবক: আপনার সন্তানের ছাত্র লগইন ব্যবহার করুন।",
  twoChildrenHint: "দুই সন্তান? সাইন ইনের পরে দ্বিতীয়জনকে যোগ করুন।",
  fillBoth: "আপনার ইউজারনেম ও পাসওয়ার্ড লিখুন।",
  triesLeft: "সাইন ইন 15 মিনিটের জন্য বন্ধ হওয়ার আগে আর {n}বার চেষ্টা করা যাবে।",
  forgotSoon: "OTP দিয়ে পাসওয়ার্ড বদল পরের বিল্ডে আসবে। ততদিন স্কুল অফিসে জিজ্ঞাসা করুন।",
  showPassword: "পাসওয়ার্ড দেখান",
  hidePassword: "পাসওয়ার্ড লুকান",
  staffSoon: "শিক্ষক ও কর্মীদের স্ক্রিন ফেজ 2-তে আসবে। এখন TatvaOS ওয়েবসাইট ব্যবহার করুন।",
  notEnabled: "{school} এখনও অ্যাপ চালু করেনি। এখন TatvaOS ওয়েবসাইট ব্যবহার করুন।",
  updateTitle: "অ্যাপটি আপডেট করুন",
  updateBody: "TatvaOS School-এর এই সংস্করণ আপনার স্কুলের জন্য পুরোনো। চালিয়ে যেতে স্টোর থেকে আপডেট করুন।",
  mustChange: "স্কুল আপনাকে একটি অস্থায়ী পাসওয়ার্ড দিয়েছে। TatvaOS ওয়েবসাইটে সেটি বদলে আবার সাইন ইন করুন।",
  signOut: "সাইন আউট",
  retry: "আবার চেষ্টা করুন",
  goodMorning: "সুপ্রভাত, {name}",
  goodAfternoon: "নমস্কার, {name}",
  goodEvening: "শুভ সন্ধ্যা, {name}",
  presentToday: "উপস্থিত",
  absentToday: "অনুপস্থিত",
  lateToday: "দেরিতে",
  notMarked: "নথিভুক্ত হয়নি",
  todayTerm: "আজ · এই মাসে {pct}%",
  homework: "হোমওয়ার্ক",
  hwToday: "আজ {n}টি",
  hwNone: "আজ নেই",
  hwOne: "আজ 1টি",
  dueOn: "{date}-এর মধ্যে দেয়",
  overdue: "মেয়াদ পেরিয়ে গেছে",
  noDues: "কোনো বকেয়া নেই",
  quickAccess: "দ্রুত যান",
  attendance: "উপস্থিতি",
  fees: "ফি",
  results: "ফলাফল",
  timetable: "রুটিন",
  notices: "নোটিস",
  library: "লাইব্রেরি",
  comingSoon: "এই স্ক্রিনটি পরের বিল্ডে আসবে।",
  notifications: "বিজ্ঞপ্তি, {n}টি না-পড়া",
  navHome: "হোম",
  navCalendar: "ক্যালেন্ডার",
  navProfile: "প্রোফাইল",
  offlineCopy: "অফলাইন। {time}-এর কপি দেখানো হচ্ছে।",
  attendanceTitle: "উপস্থিতি",
  present: "উপস্থিত",
  late: "দেরিতে",
  absent: "অনুপস্থিত",
  leave: "ছুটি",
  holidayOff: "ছুটির দিন / বন্ধ",
  days: "{n} দিন",
  day: "{n} দিন",
  prevMonth: "আগের মাস",
  nextMonth: "পরের মাস",
  applyLeave: "ছুটির আবেদন",
  pending: "অপেক্ষমাণ",
  approved: "অনুমোদিত",
  rejected: "প্রত্যাখ্যাত",
  cancelled: "বাতিল",
  noAttendance: "এই মাসে এখনও কোনো উপস্থিতি নথিভুক্ত হয়নি।",
  feesTitle: "ফি",
  totalDueNow: "এখন মোট দেয়",
  nothingDue: "এখন কিছু দেয় নেই",
  nextDue: "পরের দেয় তারিখ {date}",
  breakdown: "কী দেয়",
  fine: "জরিমানা",
  pay: "{amount} দিন",
  payComing: "অনলাইন পেমেন্ট পরের বিল্ডে আসবে। স্কুল অফিসে বা TatvaOS ওয়েবসাইটে দিতে পারেন।",
  securePayment: "নিরাপদ পেমেন্ট · UPI, কার্ড, নেট ব্যাঙ্কিং",
  receipts: "রসিদ",
  noReceipts: "এখনও কোনো রসিদ নেই।",
  paidOn: "{date}-এ জমা · {mode}",
  reverted: "স্কুল বাতিল করেছে",
  downloadReceipt: "রসিদ ডাউনলোড করুন",
  switchChild: "সন্তান বদলান",
  switchChildSub: "প্রত্যেক সন্তান নিজের স্কুল লগইনে সাইন ইন থাকে।",
  open: "খোলা",
  addChild: "সন্তান যোগ করুন",
  addChildSub: "একই স্কুল বা অন্য স্কুল",
  alertsBoth: "অন্য সন্তান খোলা থাকলেও প্রত্যেক সন্তানের বিজ্ঞপ্তি সবসময় আসে।",
  signOutOf: "{name} থেকে সাইন আউট",
  errorGeneric: "কিছু ভুল হয়েছে। আবার চেষ্টা করুন।",
  months: "জানুয়ারি,ফেব্রুয়ারি,মার্চ,এপ্রিল,মে,জুন,জুলাই,আগস্ট,সেপ্টেম্বর,অক্টোবর,নভেম্বর,ডিসেম্বর",
  weekdaysShort: "রবি,সোম,মঙ্গল,বুধ,বৃহঃ,শুক্র,শনি",
  weekdays: "রবিবার,সোমবার,মঙ্গলবার,বুধবার,বৃহস্পতিবার,শুক্রবার,শনিবার",
};

const pa: Record<StringKey, string> = {
  appName: "TatvaOS School",
  tagline: "ਪੂਰੇ ਸਕੂਲ ਲਈ ਇੱਕ ਐਪ",
  byTechvein: "Techvein ਵੱਲੋਂ",
  language: "ਪੰਜਾਬੀ",
  chooseLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
  welcomeTitle: "ਸਕੂਲ ਦੀ ਹਰ ਗੱਲ, ਇੱਕ ਐਪ ਵਿੱਚ",
  welcomeSub: "ਵਿਦਿਆਰਥੀਆਂ, ਮਾਪਿਆਂ ਅਤੇ ਅਧਿਆਪਕਾਂ ਲਈ।",
  getStarted: "ਸ਼ੁਰੂ ਕਰੋ",
  haveCode: "ਮੇਰੇ ਕੋਲ ਸਕੂਲ ਕੋਡ ਹੈ",
  previewPresent: "ਅੱਜ ਹਾਜ਼ਰ",
  previewMarked: "ਸਵੇਰੇ 8:42 ਵਜੇ ਦਰਜ",
  previewFees: "ਫ਼ੀਸ ਜਮ੍ਹਾਂ",
  previewReceipt: "ਰਸੀਦ ਤਿਆਰ",
  previewPtm: "ਸ਼ਨੀਵਾਰ ਨੂੰ PTM",
  previewNotice: "ਨਵਾਂ ਨੋਟਿਸ",
  findSchool: "ਆਪਣਾ ਸਕੂਲ ਲੱਭੋ",
  findSchoolSub: "ਇਹ ਸਿਰਫ਼ ਇੱਕ ਵਾਰ ਕਰਨਾ ਹੈ। ਇਹ ਫ਼ੋਨ ਇਸਨੂੰ ਯਾਦ ਰੱਖੇਗਾ।",
  searchPlaceholder: "ਸਕੂਲ ਦਾ ਨਾਮ ਜਾਂ ਸ਼ਹਿਰ",
  schoolCode: "ਸਕੂਲ ਕੋਡ",
  scanQr: "QR ਸਕੈਨ ਕਰੋ",
  typeThree: "ਸਕੂਲ ਦੇ ਨਾਮ ਜਾਂ ਸ਼ਹਿਰ ਦੇ ਘੱਟੋ-ਘੱਟ 3 ਅੱਖਰ ਲਿਖੋ",
  searchResults: "ਨਤੀਜੇ",
  noSchool: "ਕੋਈ ਸਕੂਲ ਨਹੀਂ ਮਿਲਿਆ। ਆਪਣੇ ਸਕੂਲ ਦਾ ਕੋਡ ਵਰਤ ਕੇ ਦੇਖੋ।",
  continue: "ਅੱਗੇ ਵਧੋ",
  enterCode: "ਆਪਣਾ ਸਕੂਲ ਕੋਡ ਲਿਖੋ",
  codePlaceholder: "ਜਿਵੇਂ DEMO",
  codeHelp: "ਕੋਡ ਸਕੂਲ ਦੇ ਨੋਟਿਸ ਜਾਂ QR ਪੋਸਟਰ ਉੱਤੇ ਹੈ।",
  check: "ਜਾਂਚੋ",
  cancel: "ਰੱਦ ਕਰੋ",
  changeSchool: "ਸਕੂਲ ਬਦਲੋ",
  signIn: "ਸਾਈਨ ਇਨ",
  usernameLabel: "ਯੂਜ਼ਰਨੇਮ ਜਾਂ ਦਾਖ਼ਲਾ ਨੰਬਰ",
  usernamePlaceholder: "ਜਿਵੇਂ DPS2026-0412",
  passwordLabel: "ਪਾਸਵਰਡ",
  keepSignedIn: "ਮੈਨੂੰ ਸਾਈਨ ਇਨ ਰੱਖੋ",
  forgot: "ਭੁੱਲ ਗਏ?",
  parentsHint: "ਮਾਪੇ: ਆਪਣੇ ਬੱਚੇ ਦਾ ਵਿਦਿਆਰਥੀ ਲੌਗਇਨ ਵਰਤੋ।",
  twoChildrenHint: "ਦੋ ਬੱਚੇ ਹਨ? ਸਾਈਨ ਇਨ ਤੋਂ ਬਾਅਦ ਦੂਜਾ ਜੋੜੋ।",
  fillBoth: "ਆਪਣਾ ਯੂਜ਼ਰਨੇਮ ਅਤੇ ਪਾਸਵਰਡ ਲਿਖੋ।",
  triesLeft: "ਸਾਈਨ ਇਨ 15 ਮਿੰਟ ਲਈ ਬੰਦ ਹੋਣ ਤੋਂ ਪਹਿਲਾਂ {n} ਕੋਸ਼ਿਸ਼ਾਂ ਬਾਕੀ ਹਨ।",
  forgotSoon: "OTP ਨਾਲ ਪਾਸਵਰਡ ਬਦਲਣਾ ਅਗਲੇ ਬਿਲਡ ਵਿੱਚ ਆਵੇਗਾ। ਉਦੋਂ ਤੱਕ ਸਕੂਲ ਦਫ਼ਤਰ ਤੋਂ ਪੁੱਛੋ।",
  showPassword: "ਪਾਸਵਰਡ ਦਿਖਾਓ",
  hidePassword: "ਪਾਸਵਰਡ ਲੁਕਾਓ",
  staffSoon: "ਅਧਿਆਪਕ ਅਤੇ ਸਟਾਫ਼ ਦੀਆਂ ਸਕ੍ਰੀਨਾਂ ਫ਼ੇਜ਼ 2 ਵਿੱਚ ਆਉਣਗੀਆਂ। ਹੁਣ TatvaOS ਵੈੱਬਸਾਈਟ ਵਰਤੋ।",
  notEnabled: "{school} ਨੇ ਅਜੇ ਐਪ ਚਾਲੂ ਨਹੀਂ ਕੀਤੀ। ਹੁਣ TatvaOS ਵੈੱਬਸਾਈਟ ਵਰਤੋ।",
  updateTitle: "ਕਿਰਪਾ ਕਰਕੇ ਐਪ ਅੱਪਡੇਟ ਕਰੋ",
  updateBody: "TatvaOS School ਦਾ ਇਹ ਸੰਸਕਰਣ ਤੁਹਾਡੇ ਸਕੂਲ ਲਈ ਪੁਰਾਣਾ ਹੈ। ਜਾਰੀ ਰੱਖਣ ਲਈ ਸਟੋਰ ਤੋਂ ਅੱਪਡੇਟ ਕਰੋ।",
  mustChange: "ਸਕੂਲ ਨੇ ਤੁਹਾਨੂੰ ਅਸਥਾਈ ਪਾਸਵਰਡ ਦਿੱਤਾ ਹੈ। ਇਸਨੂੰ TatvaOS ਵੈੱਬਸਾਈਟ ਉੱਤੇ ਬਦਲੋ, ਫਿਰ ਦੁਬਾਰਾ ਸਾਈਨ ਇਨ ਕਰੋ।",
  signOut: "ਸਾਈਨ ਆਊਟ",
  retry: "ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
  goodMorning: "ਸ਼ੁਭ ਸਵੇਰ, {name}",
  goodAfternoon: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ, {name}",
  goodEvening: "ਸ਼ੁਭ ਸ਼ਾਮ, {name}",
  presentToday: "ਹਾਜ਼ਰ",
  absentToday: "ਗ਼ੈਰਹਾਜ਼ਰ",
  lateToday: "ਦੇਰ ਨਾਲ",
  notMarked: "ਦਰਜ ਨਹੀਂ",
  todayTerm: "ਅੱਜ · ਇਸ ਮਹੀਨੇ {pct}%",
  homework: "ਹੋਮਵਰਕ",
  hwToday: "ਅੱਜ {n}",
  hwNone: "ਅੱਜ ਕੋਈ ਨਹੀਂ",
  hwOne: "ਅੱਜ 1",
  dueOn: "{date} ਤੱਕ ਦੇਣਯੋਗ",
  overdue: "ਮਿਆਦ ਲੰਘ ਗਈ",
  noDues: "ਕੋਈ ਬਕਾਇਆ ਨਹੀਂ",
  quickAccess: "ਤੁਰੰਤ ਪਹੁੰਚ",
  attendance: "ਹਾਜ਼ਰੀ",
  fees: "ਫ਼ੀਸ",
  results: "ਨਤੀਜੇ",
  timetable: "ਸਮਾਂ-ਸਾਰਣੀ",
  notices: "ਨੋਟਿਸ",
  library: "ਲਾਇਬ੍ਰੇਰੀ",
  comingSoon: "ਇਹ ਸਕ੍ਰੀਨ ਅਗਲੇ ਬਿਲਡ ਵਿੱਚ ਆਵੇਗੀ।",
  notifications: "ਸੂਚਨਾਵਾਂ, {n} ਅਣਪੜ੍ਹੀਆਂ",
  navHome: "ਹੋਮ",
  navCalendar: "ਕੈਲੰਡਰ",
  navProfile: "ਪ੍ਰੋਫ਼ਾਈਲ",
  offlineCopy: "ਆਫ਼ਲਾਈਨ। {time} ਦੀ ਕਾਪੀ ਦਿਖਾਈ ਜਾ ਰਹੀ ਹੈ।",
  attendanceTitle: "ਹਾਜ਼ਰੀ",
  present: "ਹਾਜ਼ਰ",
  late: "ਦੇਰ ਨਾਲ",
  absent: "ਗ਼ੈਰਹਾਜ਼ਰ",
  leave: "ਛੁੱਟੀ",
  holidayOff: "ਛੁੱਟੀ ਦਾ ਦਿਨ / ਬੰਦ",
  days: "{n} ਦਿਨ",
  day: "{n} ਦਿਨ",
  prevMonth: "ਪਿਛਲਾ ਮਹੀਨਾ",
  nextMonth: "ਅਗਲਾ ਮਹੀਨਾ",
  applyLeave: "ਛੁੱਟੀ ਲਈ ਅਰਜ਼ੀ",
  pending: "ਬਕਾਇਆ",
  approved: "ਮਨਜ਼ੂਰ",
  rejected: "ਨਾਮਨਜ਼ੂਰ",
  cancelled: "ਰੱਦ",
  noAttendance: "ਇਸ ਮਹੀਨੇ ਅਜੇ ਕੋਈ ਹਾਜ਼ਰੀ ਦਰਜ ਨਹੀਂ।",
  feesTitle: "ਫ਼ੀਸ",
  totalDueNow: "ਹੁਣ ਕੁੱਲ ਦੇਣਯੋਗ",
  nothingDue: "ਹੁਣ ਕੁਝ ਦੇਣਯੋਗ ਨਹੀਂ",
  nextDue: "ਅਗਲੀ ਦੇਣਯੋਗ ਤਾਰੀਖ਼ {date}",
  breakdown: "ਕੀ ਦੇਣਯੋਗ ਹੈ",
  fine: "ਜੁਰਮਾਨਾ",
  pay: "{amount} ਭੁਗਤਾਨ ਕਰੋ",
  payComing: "ਆਨਲਾਈਨ ਭੁਗਤਾਨ ਅਗਲੇ ਬਿਲਡ ਵਿੱਚ ਆਵੇਗਾ। ਤੁਸੀਂ ਸਕੂਲ ਦਫ਼ਤਰ ਜਾਂ TatvaOS ਵੈੱਬਸਾਈਟ ਉੱਤੇ ਭੁਗਤਾਨ ਕਰ ਸਕਦੇ ਹੋ।",
  securePayment: "ਸੁਰੱਖਿਅਤ ਭੁਗਤਾਨ · UPI, ਕਾਰਡ, ਨੈੱਟ ਬੈਂਕਿੰਗ",
  receipts: "ਰਸੀਦਾਂ",
  noReceipts: "ਅਜੇ ਕੋਈ ਰਸੀਦ ਨਹੀਂ।",
  paidOn: "{date} ਨੂੰ ਜਮ੍ਹਾਂ · {mode}",
  reverted: "ਸਕੂਲ ਵੱਲੋਂ ਰੱਦ",
  downloadReceipt: "ਰਸੀਦ ਡਾਊਨਲੋਡ ਕਰੋ",
  switchChild: "ਬੱਚਾ ਬਦਲੋ",
  switchChildSub: "ਹਰ ਬੱਚਾ ਆਪਣੇ ਸਕੂਲ ਲੌਗਇਨ ਨਾਲ ਸਾਈਨ ਇਨ ਰਹਿੰਦਾ ਹੈ।",
  open: "ਖੁੱਲ੍ਹਾ",
  addChild: "ਬੱਚਾ ਜੋੜੋ",
  addChildSub: "ਉਹੀ ਸਕੂਲ ਜਾਂ ਕੋਈ ਹੋਰ",
  alertsBoth: "ਹਰ ਬੱਚੇ ਦੀਆਂ ਸੂਚਨਾਵਾਂ ਹਮੇਸ਼ਾ ਆਉਂਦੀਆਂ ਹਨ, ਭਾਵੇਂ ਦੂਜਾ ਬੱਚਾ ਖੁੱਲ੍ਹਾ ਹੋਵੇ।",
  signOutOf: "{name} ਤੋਂ ਸਾਈਨ ਆਊਟ",
  errorGeneric: "ਕੁਝ ਗ਼ਲਤ ਹੋ ਗਿਆ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
  months: "ਜਨਵਰੀ,ਫ਼ਰਵਰੀ,ਮਾਰਚ,ਅਪ੍ਰੈਲ,ਮਈ,ਜੂਨ,ਜੁਲਾਈ,ਅਗਸਤ,ਸਤੰਬਰ,ਅਕਤੂਬਰ,ਨਵੰਬਰ,ਦਸੰਬਰ",
  weekdaysShort: "ਐਤ,ਸੋਮ,ਮੰਗਲ,ਬੁੱਧ,ਵੀਰ,ਸ਼ੁੱਕਰ,ਸ਼ਨੀ",
  weekdays: "ਐਤਵਾਰ,ਸੋਮਵਾਰ,ਮੰਗਲਵਾਰ,ਬੁੱਧਵਾਰ,ਵੀਰਵਾਰ,ਸ਼ੁੱਕਰਵਾਰ,ਸ਼ਨੀਵਾਰ",
};

export const strings = { en, hi, bn, pa };
export type Lang = keyof typeof strings;
export const LANGS: Lang[] = ["en", "hi", "bn", "pa"];
