// Every piece of app text, in English, Hindi, Bengali and Punjabi (SRS D-M11, NF-10).
// The Hindi, Bengali and Punjabi text must be checked by a native speaker of each before a store
// release (SRS section 13, "Done means"). {name}-style holes are filled by t().

const en = {
  appName: "TatvaOS School",
  tagline: "One app for your whole school",
  byTechvein: "by Techvein",
  language: "English",
  chooseLanguage: "Choose language",

  welcomeTitle: "Everything about school, in one app",
  welcomeSub: "For students, parents and teachers.",
  getStarted: "Get started",
  haveCode: "I have a school code",
  previewPresent: "Present today",
  previewMarked: "Marked 8:42 am",
  previewFees: "Fees paid",
  previewReceipt: "Receipt ready",
  previewPtm: "PTM Saturday",
  previewNotice: "New notice",

  findSchool: "Find your school",
  findSchoolSub: "You only do this once. We remember it on this phone.",
  searchPlaceholder: "School name or city",
  schoolCode: "School code",
  scanQr: "Scan QR",
  typeThree: "Type at least 3 letters of your school name or city",
  searchResults: "RESULTS",
  noSchool: "No school found. Try the school code from your school.",
  continue: "Continue",
  enterCode: "Enter your school code",
  codePlaceholder: "e.g. DEMO",
  codeHelp: "The code is on the school's notice or QR poster.",
  check: "Check",
  cancel: "Cancel",

  changeSchool: "Change school",
  signIn: "Sign in",
  usernameLabel: "Username or admission no.",
  usernamePlaceholder: "e.g. DPS2026-0412",
  passwordLabel: "Password",
  keepSignedIn: "Keep me signed in",
  forgot: "Forgot?",
  parentsHint: "Parents: use your child's student login.",
  twoChildrenHint: "Two children? Add the second one after signing in.",
  fillBoth: "Enter your username and password.",
  triesLeft: "{n} tries left before sign-in is locked for 15 minutes.",
  forgotSoon: "Forgot password with OTP comes in the next build. Until then, please ask the school office.",
  showPassword: "Show password",
  hidePassword: "Hide password",

  staffSoon: "The teacher and staff screens come in Phase 2. Please use the TatvaOS website for now.",
  notEnabled: "{school} has not switched on the app yet. Please use the TatvaOS website for now.",
  updateTitle: "Please update the app",
  updateBody: "This version of TatvaOS School is too old for your school. Update it from the store to continue.",
  mustChange: "Your school gave you a temporary password. Please change it on the TatvaOS website, then sign in again.",
  signOut: "Sign out",
  retry: "Try again",

  goodMorning: "Good morning, {name}",
  goodAfternoon: "Good afternoon, {name}",
  goodEvening: "Good evening, {name}",
  presentToday: "Present",
  absentToday: "Absent",
  lateToday: "Late",
  notMarked: "Not marked",
  todayTerm: "Today · {pct}% this month",
  homework: "Homework",
  hwToday: "{n} today",
  hwNone: "None today",
  hwOne: "1 today",
  dueOn: "Due {date}",
  overdue: "Overdue",
  noDues: "No dues",
  quickAccess: "Quick access",
  attendance: "Attendance",
  fees: "Fees",
  results: "Results",
  timetable: "Timetable",
  notices: "Notices",
  library: "Library",
  comingSoon: "This screen comes in the next build.",
  notifications: "Notifications, {n} unread",
  navHome: "Home",
  navCalendar: "Calendar",
  navProfile: "Profile",
  offlineCopy: "Offline. Showing the copy from {time}.",

  attendanceTitle: "Attendance",
  present: "Present",
  late: "Late",
  absent: "Absent",
  leave: "Leave",
  holidayOff: "Holiday / off",
  days: "{n} days",
  day: "{n} day",
  prevMonth: "Previous month",
  nextMonth: "Next month",
  applyLeave: "Apply for leave",
  pending: "Pending",
  approved: "Approved",
  rejected: "Rejected",
  cancelled: "Cancelled",
  noAttendance: "No attendance marked this month yet.",

  feesTitle: "Fees",
  totalDueNow: "Total due now",
  nothingDue: "Nothing due now",
  nextDue: "Next due {date}",
  breakdown: "WHAT IS DUE",
  fine: "Fine",
  pay: "Pay {amount}",
  payComing: "Online payment comes in the next build. You can pay at the school office or on the TatvaOS website.",
  securePayment: "Secure payment · UPI, cards, net banking",
  receipts: "Receipts",
  noReceipts: "No receipts yet.",
  paidOn: "Paid {date} · {mode}",
  reverted: "Cancelled by school",
  downloadReceipt: "Download receipt",

  switchChild: "Switch child",
  switchChildSub: "Each child stays signed in with their own school login.",
  open: "Open",
  addChild: "Add a child",
  addChildSub: "Same school or a different one",
  alertsBoth: "Alerts come for every child all the time, even when another child is open.",
  signOutOf: "Sign out of {name}",

  homeworkTitle: "Homework",
  noHomeworkYet: "No homework yet.",
  attachmentsN: "{n} attachments",
  attachmentOne: "1 attachment",
  attachmentsTitle: "Attachments",
  openFile: "Open",
  fileOnWebsite: "Open this file on the TatvaOS website for now.",
  byTeacher: "By {name}",
  noticesTitle: "Notices",
  noNotices: "No notices yet.",
  pinned: "Pinned",
  important: "Important",
  calendarTitle: "Calendar",
  noEvents: "Nothing on the calendar this month.",
  holidayLabel: "Holiday",
  eventLabel: "Event",
  inboxTitle: "Notifications",
  noInbox: "No notifications yet.",
  markAllRead: "Mark all as read",
  todayLabel: "Today",
  yesterdayLabel: "Yesterday",
  profileTitle: "Profile",
  admissionNo: "Admission no.",
  classLabel: "Class",
  schoolLabel: "School",
  usernameShort: "Username",
  languageLabel: "Language",
  changePassword: "Change password",
  helpSupport: "Help and support",
  callSchool: "Call the school",
  emailSchool: "Email the school",
  appVersion: "App version {v}",
  currentPassword: "Current password",
  newPassword: "New password",
  confirmPassword: "Confirm new password",
  passwordRule: "At least 8 characters, with upper and lower case letters, a number and a special character.",
  passwordsDiffer: "The two new passwords are not the same.",
  passwordWeak: "The new password does not meet the rule above.",
  passwordChanged: "Password changed. Please sign in again with the new password.",
  save: "Save",
  mustChangeTitle: "Set your own password",
  mustChangeBody: "Your school gave you a temporary password. Choose your own password to continue.",
  forgotTitle: "Forgot password",
  forgotSub: "We send a code to the mobile number or email your school has for this login.",
  sendCode: "Send code",
  codeSentTo: "We sent a code to {to}. It works for {m} minutes.",
  otpLabel: "Code",
  verify: "Verify",
  resendCode: "Send a new code",
  setNewPassword: "Set a new password",
  resetDone: "Password changed. You can sign in now.",
  backToSignIn: "Back to sign in",
  leaveTitle: "Apply for leave",
  leaveType: "Leave type",
  fromDate: "From",
  toDate: "To",
  reasonLabel: "Reason",
  reasonPlaceholder: "e.g. Fever, family function",
  submit: "Submit",
  leaveSent: "Leave request sent. You will see the school's decision here.",
  leaveDocNeeded: "For {n} days or more the school needs a document. Please apply on the TatvaOS website for now.",
  earlierDay: "Earlier day",
  laterDay: "Later day",
  fillAll: "Please fill in every field.",
  noClassesDay: "No classes on this day.",
  freePeriod: "Free",
  changedToday: "Changed today",
  noReportCards: "No report cards yet. They appear here when the school publishes them.",
  heldCard: "Held by the school until the fees are paid.",
  newLabel: "New",
  openPdf: "Open PDF",
  publishedOn: "Published {date}",
  booksWithYou: "Books with you",
  overdueBooks: "Overdue",
  libraryRule: "You can borrow {n} books for {d} days.",
  noLoans: "No library books with you now.",
  libraryFine: "Fine to pay",
  notMember: "This login is not a library member.",
  fileFailed: "The file could not be opened. Please try again.",
  unlockPrompt: "Unlock TatvaOS School",
  unlockButton: "Unlock with fingerprint",
  usePassword: "Use password instead",
  useFingerprint: "Use fingerprint next time?",
  useFingerprintSub: "Open the app with your fingerprint instead of the password.",
  turnOn: "Turn on",
  notNow: "Not now",
  fingerprintUnlock: "Fingerprint unlock",
  onLabel: "On",
  offLabel: "Off",
  sessionEnded: "{name} was signed out. Please sign in again.",
  payTitle: "Pay fees",
  payPreparing: "Getting your payment ready…",
  payTotalNote: "This total includes fines up to today.",
  payWaiting: "Waiting for the payment to be confirmed…",
  payConfirming: "The money has reached the school's bank and is being confirmed. Do not pay again.",
  paySuccess: "Payment received",
  paySuccessSub: "Receipt {no} is ready.",
  payFailed: "The payment was not completed.",
  payCancelled: "Payment cancelled.",
  payStillWaiting: "Still waiting for the bank. Check Fees again in a few minutes before paying again.",
  viewReceipt: "View receipt",
  doneLabel: "Done",
  hostelTitle: "Hostel",
  notInHostel: "You do not have a hostel room now.",
  roomLabel: "Room",
  floorLabel: "Floor",
  bedLabel: "Bed",
  blockLabel: "Block",
  wardensTitle: "Wardens",
  roommatesTitle: "Room-mates",
  callLabel: "Call",
  acRoom: "AC room",
  assignmentsTitle: "Assignments",
  noAssignments: "No assignments yet.",
  notSubmitted: "Not submitted",
  submittedStatus: "Submitted",
  checkedStatus: "Checked",
  returnedStatus: "Returned to redo",
  yourAnswer: "Your answer",
  answerPlaceholder: "Write your answer",
  takePhoto: "Take photo",
  fromGallery: "From gallery",
  addPdf: "PDF",
  maxFiles: "Up to 5 files. Photos are made smaller before sending.",
  submitAgain: "Submit again",
  submittedOk: "Submitted. Your teacher can see it now.",
  closedLabel: "The due date has passed, so this is closed.",
  pdfTooBig: "The PDF is larger than 10 MB.",
  removeFile: "Remove",
  marksLabel: "Marks",
  teacherRemark: "Teacher's remark",
  answerNeeded: "Write an answer or add a file.",
  seeAttached: "See the attached files.",
  noteLabel: "Photo of a note (optional)",
  leaveDocRequired: "For {n} days or more, the school needs a document: add a photo or PDF of it.",
  pdfTooBig5: "The PDF is larger than 5 MB.",
  errorGeneric: "Something went wrong. Please try again.",
  months: "January,February,March,April,May,June,July,August,September,October,November,December",
  weekdaysShort: "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
  weekdays: "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday",
};

export type StringKey = keyof typeof en;

const hi: Record<StringKey, string> = {
  appName: "TatvaOS School",
  tagline: "पूरे स्कूल के लिए एक ऐप",
  byTechvein: "Techvein द्वारा",
  language: "हिन्दी",
  chooseLanguage: "भाषा चुनें",
  welcomeTitle: "स्कूल की हर बात, एक ऐप में",
  welcomeSub: "छात्रों, अभिभावकों और शिक्षकों के लिए।",
  getStarted: "शुरू करें",
  haveCode: "मेरे पास स्कूल कोड है",
  previewPresent: "आज उपस्थित",
  previewMarked: "सुबह 8:42 बजे दर्ज",
  previewFees: "फ़ीस जमा",
  previewReceipt: "रसीद तैयार",
  previewPtm: "शनिवार को PTM",
  previewNotice: "नई सूचना",
  findSchool: "अपना स्कूल खोजें",
  findSchoolSub: "यह सिर्फ़ एक बार करना है। यह फ़ोन इसे याद रखेगा।",
  searchPlaceholder: "स्कूल का नाम या शहर",
  schoolCode: "स्कूल कोड",
  scanQr: "QR स्कैन करें",
  typeThree: "स्कूल के नाम या शहर के कम से कम 3 अक्षर लिखें",
  searchResults: "परिणाम",
  noSchool: "कोई स्कूल नहीं मिला। अपने स्कूल का कोड आज़माएँ।",
  continue: "आगे बढ़ें",
  enterCode: "अपना स्कूल कोड लिखें",
  codePlaceholder: "जैसे DEMO",
  codeHelp: "कोड स्कूल की सूचना या QR पोस्टर पर है।",
  check: "जाँचें",
  cancel: "रद्द करें",
  changeSchool: "स्कूल बदलें",
  signIn: "साइन इन",
  usernameLabel: "यूज़रनेम या प्रवेश संख्या",
  usernamePlaceholder: "जैसे DPS2026-0412",
  passwordLabel: "पासवर्ड",
  keepSignedIn: "मुझे साइन इन रखें",
  forgot: "भूल गए?",
  parentsHint: "अभिभावक: अपने बच्चे के छात्र लॉगिन का उपयोग करें।",
  twoChildrenHint: "दो बच्चे हैं? साइन इन के बाद दूसरा जोड़ें।",
  fillBoth: "अपना यूज़रनेम और पासवर्ड लिखें।",
  triesLeft: "साइन इन 15 मिनट के लिए बंद होने से पहले {n} कोशिशें बाकी हैं।",
  forgotSoon: "OTP से पासवर्ड बदलना अगले बिल्ड में आएगा। तब तक कृपया स्कूल ऑफ़िस से पूछें।",
  showPassword: "पासवर्ड दिखाएँ",
  hidePassword: "पासवर्ड छिपाएँ",
  staffSoon: "शिक्षक और स्टाफ़ की स्क्रीन फ़ेज़ 2 में आएँगी। अभी TatvaOS वेबसाइट का उपयोग करें।",
  notEnabled: "{school} ने अभी ऐप चालू नहीं किया है। अभी TatvaOS वेबसाइट का उपयोग करें।",
  updateTitle: "कृपया ऐप अपडेट करें",
  updateBody: "TatvaOS School का यह संस्करण आपके स्कूल के लिए पुराना है। आगे बढ़ने के लिए स्टोर से अपडेट करें।",
  mustChange: "स्कूल ने आपको अस्थायी पासवर्ड दिया है। इसे TatvaOS वेबसाइट पर बदलें, फिर दोबारा साइन इन करें।",
  signOut: "साइन आउट",
  retry: "फिर कोशिश करें",
  goodMorning: "सुप्रभात, {name}",
  goodAfternoon: "नमस्ते, {name}",
  goodEvening: "शुभ संध्या, {name}",
  presentToday: "उपस्थित",
  absentToday: "अनुपस्थित",
  lateToday: "देर से",
  notMarked: "दर्ज नहीं",
  todayTerm: "आज · इस महीने {pct}%",
  homework: "होमवर्क",
  hwToday: "आज {n}",
  hwNone: "आज कोई नहीं",
  hwOne: "आज 1",
  dueOn: "{date} तक देय",
  overdue: "देय तिथि निकल गई",
  noDues: "कोई बकाया नहीं",
  quickAccess: "त्वरित पहुँच",
  attendance: "उपस्थिति",
  fees: "फ़ीस",
  results: "परिणाम",
  timetable: "समय-सारणी",
  notices: "सूचनाएँ",
  library: "पुस्तकालय",
  comingSoon: "यह स्क्रीन अगले बिल्ड में आएगी।",
  notifications: "सूचनाएँ, {n} अपठित",
  navHome: "होम",
  navCalendar: "कैलेंडर",
  navProfile: "प्रोफ़ाइल",
  offlineCopy: "ऑफ़लाइन। {time} की कॉपी दिख रही है।",
  attendanceTitle: "उपस्थिति",
  present: "उपस्थित",
  late: "देर से",
  absent: "अनुपस्थित",
  leave: "छुट्टी",
  holidayOff: "अवकाश / बंद",
  days: "{n} दिन",
  day: "{n} दिन",
  prevMonth: "पिछला महीना",
  nextMonth: "अगला महीना",
  applyLeave: "छुट्टी के लिए आवेदन",
  pending: "लंबित",
  approved: "स्वीकृत",
  rejected: "अस्वीकृत",
  cancelled: "रद्द",
  noAttendance: "इस महीने अभी कोई उपस्थिति दर्ज नहीं है।",
  feesTitle: "फ़ीस",
  totalDueNow: "अभी कुल देय",
  nothingDue: "अभी कुछ देय नहीं",
  nextDue: "अगली देय तिथि {date}",
  breakdown: "क्या देय है",
  fine: "जुर्माना",
  pay: "{amount} भुगतान करें",
  payComing: "ऑनलाइन भुगतान अगले बिल्ड में आएगा। आप स्कूल ऑफ़िस या TatvaOS वेबसाइट पर भुगतान कर सकते हैं।",
  securePayment: "सुरक्षित भुगतान · UPI, कार्ड, नेट बैंकिंग",
  receipts: "रसीदें",
  noReceipts: "अभी कोई रसीद नहीं।",
  paidOn: "{date} को जमा · {mode}",
  reverted: "स्कूल द्वारा रद्द",
  downloadReceipt: "रसीद डाउनलोड करें",
  switchChild: "बच्चा बदलें",
  switchChildSub: "हर बच्चा अपने स्कूल लॉगिन से साइन इन रहता है।",
  open: "खुला",
  addChild: "बच्चा जोड़ें",
  addChildSub: "वही स्कूल या कोई दूसरा",
  alertsBoth: "हर बच्चे की सूचनाएँ हमेशा आती हैं, भले ही दूसरा बच्चा खुला हो।",
  signOutOf: "{name} से साइन आउट",
  homeworkTitle: "होमवर्क",
  noHomeworkYet: "अभी कोई होमवर्क नहीं।",
  attachmentsN: "{n} संलग्नक",
  attachmentOne: "1 संलग्नक",
  attachmentsTitle: "संलग्नक",
  openFile: "खोलें",
  fileOnWebsite: "अभी यह फ़ाइल TatvaOS वेबसाइट पर खोलें।",
  byTeacher: "{name} द्वारा",
  noticesTitle: "सूचनाएँ",
  noNotices: "अभी कोई सूचना नहीं।",
  pinned: "पिन किया गया",
  important: "महत्वपूर्ण",
  calendarTitle: "कैलेंडर",
  noEvents: "इस महीने कैलेंडर पर कुछ नहीं।",
  holidayLabel: "अवकाश",
  eventLabel: "कार्यक्रम",
  inboxTitle: "सूचनाएँ",
  noInbox: "अभी कोई सूचना नहीं।",
  markAllRead: "सभी को पढ़ा हुआ करें",
  todayLabel: "आज",
  yesterdayLabel: "कल",
  profileTitle: "प्रोफ़ाइल",
  admissionNo: "प्रवेश संख्या",
  classLabel: "कक्षा",
  schoolLabel: "स्कूल",
  usernameShort: "यूज़रनेम",
  languageLabel: "भाषा",
  changePassword: "पासवर्ड बदलें",
  helpSupport: "सहायता",
  callSchool: "स्कूल को फ़ोन करें",
  emailSchool: "स्कूल को ईमेल करें",
  appVersion: "ऐप संस्करण {v}",
  currentPassword: "मौजूदा पासवर्ड",
  newPassword: "नया पासवर्ड",
  confirmPassword: "नया पासवर्ड दोबारा",
  passwordRule: "कम से कम 8 अक्षर, जिनमें बड़े और छोटे अक्षर, एक अंक और एक विशेष चिह्न हो।",
  passwordsDiffer: "दोनों नए पासवर्ड एक जैसे नहीं हैं।",
  passwordWeak: "नया पासवर्ड ऊपर दिए नियम के अनुसार नहीं है।",
  passwordChanged: "पासवर्ड बदल गया। कृपया नए पासवर्ड से दोबारा साइन इन करें।",
  save: "सहेजें",
  mustChangeTitle: "अपना पासवर्ड बनाएँ",
  mustChangeBody: "स्कूल ने आपको अस्थायी पासवर्ड दिया है। आगे बढ़ने के लिए अपना पासवर्ड बनाएँ।",
  forgotTitle: "पासवर्ड भूल गए",
  forgotSub: "हम इस लॉगिन के लिए स्कूल के पास दर्ज मोबाइल नंबर या ईमेल पर एक कोड भेजेंगे।",
  sendCode: "कोड भेजें",
  codeSentTo: "हमने {to} पर कोड भेजा है। यह {m} मिनट तक चलेगा।",
  otpLabel: "कोड",
  verify: "जाँचें",
  resendCode: "नया कोड भेजें",
  setNewPassword: "नया पासवर्ड बनाएँ",
  resetDone: "पासवर्ड बदल गया। अब आप साइन इन कर सकते हैं।",
  backToSignIn: "साइन इन पर वापस",
  leaveTitle: "छुट्टी के लिए आवेदन",
  leaveType: "छुट्टी का प्रकार",
  fromDate: "से",
  toDate: "तक",
  reasonLabel: "कारण",
  reasonPlaceholder: "जैसे बुखार, पारिवारिक कार्यक्रम",
  submit: "जमा करें",
  leaveSent: "छुट्टी का आवेदन भेजा गया। स्कूल का फ़ैसला यहीं दिखेगा।",
  leaveDocNeeded: "{n} या अधिक दिनों के लिए स्कूल को दस्तावेज़ चाहिए। अभी TatvaOS वेबसाइट पर आवेदन करें।",
  earlierDay: "पिछला दिन",
  laterDay: "अगला दिन",
  fillAll: "कृपया सभी जानकारी भरें।",
  noClassesDay: "इस दिन कोई कक्षा नहीं।",
  freePeriod: "खाली",
  changedToday: "आज बदला गया",
  noReportCards: "अभी कोई रिपोर्ट कार्ड नहीं। स्कूल के प्रकाशित करने पर यहाँ दिखेंगे।",
  heldCard: "फ़ीस जमा होने तक स्कूल ने इसे रोका है।",
  newLabel: "नया",
  openPdf: "PDF खोलें",
  publishedOn: "{date} को प्रकाशित",
  booksWithYou: "आपके पास किताबें",
  overdueBooks: "देर से",
  libraryRule: "आप {n} किताबें {d} दिन के लिए ले सकते हैं।",
  noLoans: "अभी आपके पास पुस्तकालय की कोई किताब नहीं।",
  libraryFine: "देय जुर्माना",
  notMember: "यह लॉगिन पुस्तकालय का सदस्य नहीं है।",
  fileFailed: "फ़ाइल नहीं खुल सकी। कृपया फिर कोशिश करें।",
  unlockPrompt: "TatvaOS School खोलें",
  unlockButton: "फ़िंगरप्रिंट से खोलें",
  usePassword: "इसके बजाय पासवर्ड से",
  useFingerprint: "अगली बार फ़िंगरप्रिंट से खोलें?",
  useFingerprintSub: "पासवर्ड की जगह फ़िंगरप्रिंट से ऐप खोलें।",
  turnOn: "चालू करें",
  notNow: "अभी नहीं",
  fingerprintUnlock: "फ़िंगरप्रिंट से खोलना",
  onLabel: "चालू",
  offLabel: "बंद",
  sessionEnded: "{name} साइन आउट हो गए। कृपया दोबारा साइन इन करें।",
  payTitle: "फ़ीस भुगतान",
  payPreparing: "भुगतान तैयार हो रहा है…",
  payTotalNote: "इस कुल में आज तक का जुर्माना शामिल है।",
  payWaiting: "भुगतान की पुष्टि का इंतज़ार…",
  payConfirming: "पैसा स्कूल के बैंक तक पहुँच गया है और पुष्टि हो रही है। दोबारा भुगतान न करें।",
  paySuccess: "भुगतान प्राप्त हुआ",
  paySuccessSub: "रसीद {no} तैयार है।",
  payFailed: "भुगतान पूरा नहीं हुआ।",
  payCancelled: "भुगतान रद्द किया गया।",
  payStillWaiting: "बैंक का अब भी इंतज़ार है। दोबारा भुगतान से पहले कुछ मिनट बाद फ़ीस देखें।",
  viewReceipt: "रसीद देखें",
  doneLabel: "हो गया",
  hostelTitle: "छात्रावास",
  notInHostel: "अभी आपके पास छात्रावास का कमरा नहीं है।",
  roomLabel: "कमरा",
  floorLabel: "मंज़िल",
  bedLabel: "बिस्तर",
  blockLabel: "ब्लॉक",
  wardensTitle: "वार्डन",
  roommatesTitle: "कमरे के साथी",
  callLabel: "फ़ोन करें",
  acRoom: "AC कमरा",
  assignmentsTitle: "असाइनमेंट",
  noAssignments: "अभी कोई असाइनमेंट नहीं।",
  notSubmitted: "जमा नहीं",
  submittedStatus: "जमा किया",
  checkedStatus: "जाँचा गया",
  returnedStatus: "दोबारा करने को लौटाया",
  yourAnswer: "आपका उत्तर",
  answerPlaceholder: "अपना उत्तर लिखें",
  takePhoto: "फ़ोटो लें",
  fromGallery: "गैलरी से",
  addPdf: "PDF",
  maxFiles: "अधिकतम 5 फ़ाइलें। भेजने से पहले फ़ोटो छोटी की जाती हैं।",
  submitAgain: "दोबारा जमा करें",
  submittedOk: "जमा हो गया। आपके शिक्षक अब इसे देख सकते हैं।",
  closedLabel: "अंतिम तिथि निकल गई है, इसलिए यह बंद है।",
  pdfTooBig: "PDF 10 MB से बड़ी है।",
  removeFile: "हटाएँ",
  marksLabel: "अंक",
  teacherRemark: "शिक्षक की टिप्पणी",
  answerNeeded: "उत्तर लिखें या फ़ाइल जोड़ें।",
  seeAttached: "संलग्न फ़ाइलें देखें।",
  noteLabel: "नोट की फ़ोटो (वैकल्पिक)",
  leaveDocRequired: "{n} या अधिक दिनों के लिए स्कूल को दस्तावेज़ चाहिए: उसकी फ़ोटो या PDF जोड़ें।",
  pdfTooBig5: "PDF 5 MB से बड़ी है।",
  errorGeneric: "कुछ गलत हो गया। कृपया फिर कोशिश करें।",
  months: "जनवरी,फ़रवरी,मार्च,अप्रैल,मई,जून,जुलाई,अगस्त,सितंबर,अक्टूबर,नवंबर,दिसंबर",
  weekdaysShort: "रवि,सोम,मंगल,बुध,गुरु,शुक्र,शनि",
  weekdays: "रविवार,सोमवार,मंगलवार,बुधवार,गुरुवार,शुक्रवार,शनिवार",
};

const bn: Record<StringKey, string> = {
  appName: "TatvaOS School",
  tagline: "পুরো স্কুলের জন্য একটি অ্যাপ",
  byTechvein: "Techvein-এর তৈরি",
  language: "বাংলা",
  chooseLanguage: "ভাষা বেছে নিন",
  welcomeTitle: "স্কুলের সব কিছু, একটি অ্যাপে",
  welcomeSub: "ছাত্রছাত্রী, অভিভাবক ও শিক্ষকদের জন্য।",
  getStarted: "শুরু করুন",
  haveCode: "আমার কাছে স্কুল কোড আছে",
  previewPresent: "আজ উপস্থিত",
  previewMarked: "সকাল 8:42-এ নথিভুক্ত",
  previewFees: "ফি জমা হয়েছে",
  previewReceipt: "রসিদ তৈরি",
  previewPtm: "শনিবার PTM",
  previewNotice: "নতুন নোটিস",
  findSchool: "আপনার স্কুল খুঁজুন",
  findSchoolSub: "এটা একবারই করতে হবে। এই ফোন মনে রাখবে।",
  searchPlaceholder: "স্কুলের নাম বা শহর",
  schoolCode: "স্কুল কোড",
  scanQr: "QR স্ক্যান করুন",
  typeThree: "স্কুলের নাম বা শহরের অন্তত 3টি অক্ষর লিখুন",
  searchResults: "ফলাফল",
  noSchool: "কোনো স্কুল পাওয়া যায়নি। আপনার স্কুলের কোড দিয়ে চেষ্টা করুন।",
  continue: "এগিয়ে যান",
  enterCode: "আপনার স্কুল কোড লিখুন",
  codePlaceholder: "যেমন DEMO",
  codeHelp: "কোডটি স্কুলের নোটিস বা QR পোস্টারে আছে।",
  check: "যাচাই করুন",
  cancel: "বাতিল",
  changeSchool: "স্কুল বদলান",
  signIn: "সাইন ইন",
  usernameLabel: "ইউজারনেম বা ভর্তি নম্বর",
  usernamePlaceholder: "যেমন DPS2026-0412",
  passwordLabel: "পাসওয়ার্ড",
  keepSignedIn: "আমাকে সাইন ইন রাখুন",
  forgot: "ভুলে গেছেন?",
  parentsHint: "অভিভাবক: আপনার সন্তানের ছাত্র লগইন ব্যবহার করুন।",
  twoChildrenHint: "দুই সন্তান? সাইন ইনের পরে দ্বিতীয়জনকে যোগ করুন।",
  fillBoth: "আপনার ইউজারনেম ও পাসওয়ার্ড লিখুন।",
  triesLeft: "সাইন ইন 15 মিনিটের জন্য বন্ধ হওয়ার আগে আর {n}বার চেষ্টা করা যাবে।",
  forgotSoon: "OTP দিয়ে পাসওয়ার্ড বদল পরের বিল্ডে আসবে। ততদিন স্কুল অফিসে জিজ্ঞাসা করুন।",
  showPassword: "পাসওয়ার্ড দেখান",
  hidePassword: "পাসওয়ার্ড লুকান",
  staffSoon: "শিক্ষক ও কর্মীদের স্ক্রিন ফেজ 2-তে আসবে। এখন TatvaOS ওয়েবসাইট ব্যবহার করুন।",
  notEnabled: "{school} এখনও অ্যাপ চালু করেনি। এখন TatvaOS ওয়েবসাইট ব্যবহার করুন।",
  updateTitle: "অ্যাপটি আপডেট করুন",
  updateBody: "TatvaOS School-এর এই সংস্করণ আপনার স্কুলের জন্য পুরোনো। চালিয়ে যেতে স্টোর থেকে আপডেট করুন।",
  mustChange: "স্কুল আপনাকে একটি অস্থায়ী পাসওয়ার্ড দিয়েছে। TatvaOS ওয়েবসাইটে সেটি বদলে আবার সাইন ইন করুন।",
  signOut: "সাইন আউট",
  retry: "আবার চেষ্টা করুন",
  goodMorning: "সুপ্রভাত, {name}",
  goodAfternoon: "নমস্কার, {name}",
  goodEvening: "শুভ সন্ধ্যা, {name}",
  presentToday: "উপস্থিত",
  absentToday: "অনুপস্থিত",
  lateToday: "দেরিতে",
  notMarked: "নথিভুক্ত হয়নি",
  todayTerm: "আজ · এই মাসে {pct}%",
  homework: "হোমওয়ার্ক",
  hwToday: "আজ {n}টি",
  hwNone: "আজ নেই",
  hwOne: "আজ 1টি",
  dueOn: "{date}-এর মধ্যে দেয়",
  overdue: "মেয়াদ পেরিয়ে গেছে",
  noDues: "কোনো বকেয়া নেই",
  quickAccess: "দ্রুত যান",
  attendance: "উপস্থিতি",
  fees: "ফি",
  results: "ফলাফল",
  timetable: "রুটিন",
  notices: "নোটিস",
  library: "লাইব্রেরি",
  comingSoon: "এই স্ক্রিনটি পরের বিল্ডে আসবে।",
  notifications: "বিজ্ঞপ্তি, {n}টি না-পড়া",
  navHome: "হোম",
  navCalendar: "ক্যালেন্ডার",
  navProfile: "প্রোফাইল",
  offlineCopy: "অফলাইন। {time}-এর কপি দেখানো হচ্ছে।",
  attendanceTitle: "উপস্থিতি",
  present: "উপস্থিত",
  late: "দেরিতে",
  absent: "অনুপস্থিত",
  leave: "ছুটি",
  holidayOff: "ছুটির দিন / বন্ধ",
  days: "{n} দিন",
  day: "{n} দিন",
  prevMonth: "আগের মাস",
  nextMonth: "পরের মাস",
  applyLeave: "ছুটির আবেদন",
  pending: "অপেক্ষমাণ",
  approved: "অনুমোদিত",
  rejected: "প্রত্যাখ্যাত",
  cancelled: "বাতিল",
  noAttendance: "এই মাসে এখনও কোনো উপস্থিতি নথিভুক্ত হয়নি।",
  feesTitle: "ফি",
  totalDueNow: "এখন মোট দেয়",
  nothingDue: "এখন কিছু দেয় নেই",
  nextDue: "পরের দেয় তারিখ {date}",
  breakdown: "কী দেয়",
  fine: "জরিমানা",
  pay: "{amount} দিন",
  payComing: "অনলাইন পেমেন্ট পরের বিল্ডে আসবে। স্কুল অফিসে বা TatvaOS ওয়েবসাইটে দিতে পারেন।",
  securePayment: "নিরাপদ পেমেন্ট · UPI, কার্ড, নেট ব্যাঙ্কিং",
  receipts: "রসিদ",
  noReceipts: "এখনও কোনো রসিদ নেই।",
  paidOn: "{date}-এ জমা · {mode}",
  reverted: "স্কুল বাতিল করেছে",
  downloadReceipt: "রসিদ ডাউনলোড করুন",
  switchChild: "সন্তান বদলান",
  switchChildSub: "প্রত্যেক সন্তান নিজের স্কুল লগইনে সাইন ইন থাকে।",
  open: "খোলা",
  addChild: "সন্তান যোগ করুন",
  addChildSub: "একই স্কুল বা অন্য স্কুল",
  alertsBoth: "অন্য সন্তান খোলা থাকলেও প্রত্যেক সন্তানের বিজ্ঞপ্তি সবসময় আসে।",
  signOutOf: "{name} থেকে সাইন আউট",
  homeworkTitle: "হোমওয়ার্ক",
  noHomeworkYet: "এখনও কোনো হোমওয়ার্ক নেই।",
  attachmentsN: "{n}টি সংযুক্তি",
  attachmentOne: "1টি সংযুক্তি",
  attachmentsTitle: "সংযুক্তি",
  openFile: "খুলুন",
  fileOnWebsite: "এখন এই ফাইলটি TatvaOS ওয়েবসাইটে খুলুন।",
  byTeacher: "{name}-এর দেওয়া",
  noticesTitle: "নোটিস",
  noNotices: "এখনও কোনো নোটিস নেই।",
  pinned: "পিন করা",
  important: "গুরুত্বপূর্ণ",
  calendarTitle: "ক্যালেন্ডার",
  noEvents: "এই মাসে ক্যালেন্ডারে কিছু নেই।",
  holidayLabel: "ছুটি",
  eventLabel: "অনুষ্ঠান",
  inboxTitle: "বিজ্ঞপ্তি",
  noInbox: "এখনও কোনো বিজ্ঞপ্তি নেই।",
  markAllRead: "সব পড়া হয়েছে করুন",
  todayLabel: "আজ",
  yesterdayLabel: "গতকাল",
  profileTitle: "প্রোফাইল",
  admissionNo: "ভর্তি নম্বর",
  classLabel: "শ্রেণি",
  schoolLabel: "স্কুল",
  usernameShort: "ইউজারনেম",
  languageLabel: "ভাষা",
  changePassword: "পাসওয়ার্ড বদলান",
  helpSupport: "সাহায্য",
  callSchool: "স্কুলে ফোন করুন",
  emailSchool: "স্কুলে ইমেল করুন",
  appVersion: "অ্যাপ সংস্করণ {v}",
  currentPassword: "বর্তমান পাসওয়ার্ড",
  newPassword: "নতুন পাসওয়ার্ড",
  confirmPassword: "নতুন পাসওয়ার্ড আবার",
  passwordRule: "অন্তত 8টি অক্ষর, যাতে বড় ও ছোট হাতের অক্ষর, একটি সংখ্যা ও একটি বিশেষ চিহ্ন থাকবে।",
  passwordsDiffer: "দুটি নতুন পাসওয়ার্ড এক নয়।",
  passwordWeak: "নতুন পাসওয়ার্ড উপরের নিয়ম মানেনি।",
  passwordChanged: "পাসওয়ার্ড বদলেছে। নতুন পাসওয়ার্ড দিয়ে আবার সাইন ইন করুন।",
  save: "সংরক্ষণ করুন",
  mustChangeTitle: "নিজের পাসওয়ার্ড দিন",
  mustChangeBody: "স্কুল আপনাকে একটি অস্থায়ী পাসওয়ার্ড দিয়েছে। চালিয়ে যেতে নিজের পাসওয়ার্ড দিন।",
  forgotTitle: "পাসওয়ার্ড ভুলে গেছেন",
  forgotSub: "এই লগইনের জন্য স্কুলের কাছে থাকা মোবাইল নম্বর বা ইমেলে আমরা একটি কোড পাঠাব।",
  sendCode: "কোড পাঠান",
  codeSentTo: "আমরা {to}-তে কোড পাঠিয়েছি। এটি {m} মিনিট চলবে।",
  otpLabel: "কোড",
  verify: "যাচাই করুন",
  resendCode: "নতুন কোড পাঠান",
  setNewPassword: "নতুন পাসওয়ার্ড দিন",
  resetDone: "পাসওয়ার্ড বদলেছে। এখন সাইন ইন করতে পারেন।",
  backToSignIn: "সাইন ইনে ফিরুন",
  leaveTitle: "ছুটির আবেদন",
  leaveType: "ছুটির ধরন",
  fromDate: "থেকে",
  toDate: "পর্যন্ত",
  reasonLabel: "কারণ",
  reasonPlaceholder: "যেমন জ্বর, পারিবারিক অনুষ্ঠান",
  submit: "জমা দিন",
  leaveSent: "ছুটির আবেদন পাঠানো হয়েছে। স্কুলের সিদ্ধান্ত এখানেই দেখা যাবে।",
  leaveDocNeeded: "{n} বা তার বেশি দিনের জন্য স্কুলের একটি নথি লাগে। এখন TatvaOS ওয়েবসাইটে আবেদন করুন।",
  earlierDay: "আগের দিন",
  laterDay: "পরের দিন",
  fillAll: "অনুগ্রহ করে সব ঘর পূরণ করুন।",
  noClassesDay: "এই দিনে কোনো ক্লাস নেই।",
  freePeriod: "ফাঁকা",
  changedToday: "আজ বদলানো হয়েছে",
  noReportCards: "এখনও কোনো রিপোর্ট কার্ড নেই। স্কুল প্রকাশ করলে এখানে দেখা যাবে।",
  heldCard: "ফি জমা না হওয়া পর্যন্ত স্কুল এটি আটকে রেখেছে।",
  newLabel: "নতুন",
  openPdf: "PDF খুলুন",
  publishedOn: "{date}-এ প্রকাশিত",
  booksWithYou: "আপনার কাছে বই",
  overdueBooks: "মেয়াদ পেরিয়েছে",
  libraryRule: "আপনি {n}টি বই {d} দিনের জন্য নিতে পারেন।",
  noLoans: "এখন আপনার কাছে লাইব্রেরির কোনো বই নেই।",
  libraryFine: "দেয় জরিমানা",
  notMember: "এই লগইন লাইব্রেরির সদস্য নয়।",
  fileFailed: "ফাইলটি খোলা যায়নি। আবার চেষ্টা করুন।",
  unlockPrompt: "TatvaOS School খুলুন",
  unlockButton: "ফিঙ্গারপ্রিন্ট দিয়ে খুলুন",
  usePassword: "এর বদলে পাসওয়ার্ড দিয়ে",
  useFingerprint: "পরের বার ফিঙ্গারপ্রিন্ট দিয়ে খুলবেন?",
  useFingerprintSub: "পাসওয়ার্ডের বদলে ফিঙ্গারপ্রিন্ট দিয়ে অ্যাপ খুলুন।",
  turnOn: "চালু করুন",
  notNow: "এখন নয়",
  fingerprintUnlock: "ফিঙ্গারপ্রিন্ট দিয়ে খোলা",
  onLabel: "চালু",
  offLabel: "বন্ধ",
  sessionEnded: "{name} সাইন আউট হয়ে গেছে। আবার সাইন ইন করুন।",
  payTitle: "ফি জমা",
  payPreparing: "পেমেন্ট তৈরি হচ্ছে…",
  payTotalNote: "এই মোটের মধ্যে আজ পর্যন্ত জরিমানা ধরা আছে।",
  payWaiting: "পেমেন্ট নিশ্চিত হওয়ার অপেক্ষা…",
  payConfirming: "টাকা স্কুলের ব্যাঙ্কে পৌঁছেছে, নিশ্চিত করা হচ্ছে। আবার টাকা দেবেন না।",
  paySuccess: "পেমেন্ট পাওয়া গেছে",
  paySuccessSub: "রসিদ {no} তৈরি।",
  payFailed: "পেমেন্ট সম্পূর্ণ হয়নি।",
  payCancelled: "পেমেন্ট বাতিল হয়েছে।",
  payStillWaiting: "এখনও ব্যাঙ্কের অপেক্ষা। আবার টাকা দেওয়ার আগে কয়েক মিনিট পরে ফি দেখুন।",
  viewReceipt: "রসিদ দেখুন",
  doneLabel: "হয়ে গেছে",
  hostelTitle: "হোস্টেল",
  notInHostel: "এখন আপনার হোস্টেলের ঘর নেই।",
  roomLabel: "ঘর",
  floorLabel: "তলা",
  bedLabel: "বিছানা",
  blockLabel: "ব্লক",
  wardensTitle: "ওয়ার্ডেন",
  roommatesTitle: "ঘরের সঙ্গী",
  callLabel: "ফোন করুন",
  acRoom: "AC ঘর",
  assignmentsTitle: "অ্যাসাইনমেন্ট",
  noAssignments: "এখনও কোনো অ্যাসাইনমেন্ট নেই।",
  notSubmitted: "জমা হয়নি",
  submittedStatus: "জমা হয়েছে",
  checkedStatus: "দেখা হয়েছে",
  returnedStatus: "আবার করতে ফেরত",
  yourAnswer: "আপনার উত্তর",
  answerPlaceholder: "আপনার উত্তর লিখুন",
  takePhoto: "ছবি তুলুন",
  fromGallery: "গ্যালারি থেকে",
  addPdf: "PDF",
  maxFiles: "সর্বোচ্চ 5টি ফাইল। পাঠানোর আগে ছবি ছোট করা হয়।",
  submitAgain: "আবার জমা দিন",
  submittedOk: "জমা হয়েছে। আপনার শিক্ষক এখন এটি দেখতে পাবেন।",
  closedLabel: "শেষ তারিখ পেরিয়ে গেছে, তাই এটি বন্ধ।",
  pdfTooBig: "PDF 10 MB-এর চেয়ে বড়।",
  removeFile: "সরান",
  marksLabel: "নম্বর",
  teacherRemark: "শিক্ষকের মন্তব্য",
  answerNeeded: "উত্তর লিখুন বা ফাইল যোগ করুন।",
  seeAttached: "সংযুক্ত ফাইল দেখুন।",
  noteLabel: "নোটের ছবি (ঐচ্ছিক)",
  leaveDocRequired: "{n} বা তার বেশি দিনের জন্য স্কুলের নথি লাগে: তার ছবি বা PDF যোগ করুন।",
  pdfTooBig5: "PDF 5 MB-এর চেয়ে বড়।",
  errorGeneric: "কিছু ভুল হয়েছে। আবার চেষ্টা করুন।",
  months: "জানুয়ারি,ফেব্রুয়ারি,মার্চ,এপ্রিল,মে,জুন,জুলাই,আগস্ট,সেপ্টেম্বর,অক্টোবর,নভেম্বর,ডিসেম্বর",
  weekdaysShort: "রবি,সোম,মঙ্গল,বুধ,বৃহঃ,শুক্র,শনি",
  weekdays: "রবিবার,সোমবার,মঙ্গলবার,বুধবার,বৃহস্পতিবার,শুক্রবার,শনিবার",
};

const pa: Record<StringKey, string> = {
  appName: "TatvaOS School",
  tagline: "ਪੂਰੇ ਸਕੂਲ ਲਈ ਇੱਕ ਐਪ",
  byTechvein: "Techvein ਵੱਲੋਂ",
  language: "ਪੰਜਾਬੀ",
  chooseLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
  welcomeTitle: "ਸਕੂਲ ਦੀ ਹਰ ਗੱਲ, ਇੱਕ ਐਪ ਵਿੱਚ",
  welcomeSub: "ਵਿਦਿਆਰਥੀਆਂ, ਮਾਪਿਆਂ ਅਤੇ ਅਧਿਆਪਕਾਂ ਲਈ।",
  getStarted: "ਸ਼ੁਰੂ ਕਰੋ",
  haveCode: "ਮੇਰੇ ਕੋਲ ਸਕੂਲ ਕੋਡ ਹੈ",
  previewPresent: "ਅੱਜ ਹਾਜ਼ਰ",
  previewMarked: "ਸਵੇਰੇ 8:42 ਵਜੇ ਦਰਜ",
  previewFees: "ਫ਼ੀਸ ਜਮ੍ਹਾਂ",
  previewReceipt: "ਰਸੀਦ ਤਿਆਰ",
  previewPtm: "ਸ਼ਨੀਵਾਰ ਨੂੰ PTM",
  previewNotice: "ਨਵਾਂ ਨੋਟਿਸ",
  findSchool: "ਆਪਣਾ ਸਕੂਲ ਲੱਭੋ",
  findSchoolSub: "ਇਹ ਸਿਰਫ਼ ਇੱਕ ਵਾਰ ਕਰਨਾ ਹੈ। ਇਹ ਫ਼ੋਨ ਇਸਨੂੰ ਯਾਦ ਰੱਖੇਗਾ।",
  searchPlaceholder: "ਸਕੂਲ ਦਾ ਨਾਮ ਜਾਂ ਸ਼ਹਿਰ",
  schoolCode: "ਸਕੂਲ ਕੋਡ",
  scanQr: "QR ਸਕੈਨ ਕਰੋ",
  typeThree: "ਸਕੂਲ ਦੇ ਨਾਮ ਜਾਂ ਸ਼ਹਿਰ ਦੇ ਘੱਟੋ-ਘੱਟ 3 ਅੱਖਰ ਲਿਖੋ",
  searchResults: "ਨਤੀਜੇ",
  noSchool: "ਕੋਈ ਸਕੂਲ ਨਹੀਂ ਮਿਲਿਆ। ਆਪਣੇ ਸਕੂਲ ਦਾ ਕੋਡ ਵਰਤ ਕੇ ਦੇਖੋ।",
  continue: "ਅੱਗੇ ਵਧੋ",
  enterCode: "ਆਪਣਾ ਸਕੂਲ ਕੋਡ ਲਿਖੋ",
  codePlaceholder: "ਜਿਵੇਂ DEMO",
  codeHelp: "ਕੋਡ ਸਕੂਲ ਦੇ ਨੋਟਿਸ ਜਾਂ QR ਪੋਸਟਰ ਉੱਤੇ ਹੈ।",
  check: "ਜਾਂਚੋ",
  cancel: "ਰੱਦ ਕਰੋ",
  changeSchool: "ਸਕੂਲ ਬਦਲੋ",
  signIn: "ਸਾਈਨ ਇਨ",
  usernameLabel: "ਯੂਜ਼ਰਨੇਮ ਜਾਂ ਦਾਖ਼ਲਾ ਨੰਬਰ",
  usernamePlaceholder: "ਜਿਵੇਂ DPS2026-0412",
  passwordLabel: "ਪਾਸਵਰਡ",
  keepSignedIn: "ਮੈਨੂੰ ਸਾਈਨ ਇਨ ਰੱਖੋ",
  forgot: "ਭੁੱਲ ਗਏ?",
  parentsHint: "ਮਾਪੇ: ਆਪਣੇ ਬੱਚੇ ਦਾ ਵਿਦਿਆਰਥੀ ਲੌਗਇਨ ਵਰਤੋ।",
  twoChildrenHint: "ਦੋ ਬੱਚੇ ਹਨ? ਸਾਈਨ ਇਨ ਤੋਂ ਬਾਅਦ ਦੂਜਾ ਜੋੜੋ।",
  fillBoth: "ਆਪਣਾ ਯੂਜ਼ਰਨੇਮ ਅਤੇ ਪਾਸਵਰਡ ਲਿਖੋ।",
  triesLeft: "ਸਾਈਨ ਇਨ 15 ਮਿੰਟ ਲਈ ਬੰਦ ਹੋਣ ਤੋਂ ਪਹਿਲਾਂ {n} ਕੋਸ਼ਿਸ਼ਾਂ ਬਾਕੀ ਹਨ।",
  forgotSoon: "OTP ਨਾਲ ਪਾਸਵਰਡ ਬਦਲਣਾ ਅਗਲੇ ਬਿਲਡ ਵਿੱਚ ਆਵੇਗਾ। ਉਦੋਂ ਤੱਕ ਸਕੂਲ ਦਫ਼ਤਰ ਤੋਂ ਪੁੱਛੋ।",
  showPassword: "ਪਾਸਵਰਡ ਦਿਖਾਓ",
  hidePassword: "ਪਾਸਵਰਡ ਲੁਕਾਓ",
  staffSoon: "ਅਧਿਆਪਕ ਅਤੇ ਸਟਾਫ਼ ਦੀਆਂ ਸਕ੍ਰੀਨਾਂ ਫ਼ੇਜ਼ 2 ਵਿੱਚ ਆਉਣਗੀਆਂ। ਹੁਣ TatvaOS ਵੈੱਬਸਾਈਟ ਵਰਤੋ।",
  notEnabled: "{school} ਨੇ ਅਜੇ ਐਪ ਚਾਲੂ ਨਹੀਂ ਕੀਤੀ। ਹੁਣ TatvaOS ਵੈੱਬਸਾਈਟ ਵਰਤੋ।",
  updateTitle: "ਕਿਰਪਾ ਕਰਕੇ ਐਪ ਅੱਪਡੇਟ ਕਰੋ",
  updateBody: "TatvaOS School ਦਾ ਇਹ ਸੰਸਕਰਣ ਤੁਹਾਡੇ ਸਕੂਲ ਲਈ ਪੁਰਾਣਾ ਹੈ। ਜਾਰੀ ਰੱਖਣ ਲਈ ਸਟੋਰ ਤੋਂ ਅੱਪਡੇਟ ਕਰੋ।",
  mustChange: "ਸਕੂਲ ਨੇ ਤੁਹਾਨੂੰ ਅਸਥਾਈ ਪਾਸਵਰਡ ਦਿੱਤਾ ਹੈ। ਇਸਨੂੰ TatvaOS ਵੈੱਬਸਾਈਟ ਉੱਤੇ ਬਦਲੋ, ਫਿਰ ਦੁਬਾਰਾ ਸਾਈਨ ਇਨ ਕਰੋ।",
  signOut: "ਸਾਈਨ ਆਊਟ",
  retry: "ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
  goodMorning: "ਸ਼ੁਭ ਸਵੇਰ, {name}",
  goodAfternoon: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ, {name}",
  goodEvening: "ਸ਼ੁਭ ਸ਼ਾਮ, {name}",
  presentToday: "ਹਾਜ਼ਰ",
  absentToday: "ਗ਼ੈਰਹਾਜ਼ਰ",
  lateToday: "ਦੇਰ ਨਾਲ",
  notMarked: "ਦਰਜ ਨਹੀਂ",
  todayTerm: "ਅੱਜ · ਇਸ ਮਹੀਨੇ {pct}%",
  homework: "ਹੋਮਵਰਕ",
  hwToday: "ਅੱਜ {n}",
  hwNone: "ਅੱਜ ਕੋਈ ਨਹੀਂ",
  hwOne: "ਅੱਜ 1",
  dueOn: "{date} ਤੱਕ ਦੇਣਯੋਗ",
  overdue: "ਮਿਆਦ ਲੰਘ ਗਈ",
  noDues: "ਕੋਈ ਬਕਾਇਆ ਨਹੀਂ",
  quickAccess: "ਤੁਰੰਤ ਪਹੁੰਚ",
  attendance: "ਹਾਜ਼ਰੀ",
  fees: "ਫ਼ੀਸ",
  results: "ਨਤੀਜੇ",
  timetable: "ਸਮਾਂ-ਸਾਰਣੀ",
  notices: "ਨੋਟਿਸ",
  library: "ਲਾਇਬ੍ਰੇਰੀ",
  comingSoon: "ਇਹ ਸਕ੍ਰੀਨ ਅਗਲੇ ਬਿਲਡ ਵਿੱਚ ਆਵੇਗੀ।",
  notifications: "ਸੂਚਨਾਵਾਂ, {n} ਅਣਪੜ੍ਹੀਆਂ",
  navHome: "ਹੋਮ",
  navCalendar: "ਕੈਲੰਡਰ",
  navProfile: "ਪ੍ਰੋਫ਼ਾਈਲ",
  offlineCopy: "ਆਫ਼ਲਾਈਨ। {time} ਦੀ ਕਾਪੀ ਦਿਖਾਈ ਜਾ ਰਹੀ ਹੈ।",
  attendanceTitle: "ਹਾਜ਼ਰੀ",
  present: "ਹਾਜ਼ਰ",
  late: "ਦੇਰ ਨਾਲ",
  absent: "ਗ਼ੈਰਹਾਜ਼ਰ",
  leave: "ਛੁੱਟੀ",
  holidayOff: "ਛੁੱਟੀ ਦਾ ਦਿਨ / ਬੰਦ",
  days: "{n} ਦਿਨ",
  day: "{n} ਦਿਨ",
  prevMonth: "ਪਿਛਲਾ ਮਹੀਨਾ",
  nextMonth: "ਅਗਲਾ ਮਹੀਨਾ",
  applyLeave: "ਛੁੱਟੀ ਲਈ ਅਰਜ਼ੀ",
  pending: "ਬਕਾਇਆ",
  approved: "ਮਨਜ਼ੂਰ",
  rejected: "ਨਾਮਨਜ਼ੂਰ",
  cancelled: "ਰੱਦ",
  noAttendance: "ਇਸ ਮਹੀਨੇ ਅਜੇ ਕੋਈ ਹਾਜ਼ਰੀ ਦਰਜ ਨਹੀਂ।",
  feesTitle: "ਫ਼ੀਸ",
  totalDueNow: "ਹੁਣ ਕੁੱਲ ਦੇਣਯੋਗ",
  nothingDue: "ਹੁਣ ਕੁਝ ਦੇਣਯੋਗ ਨਹੀਂ",
  nextDue: "ਅਗਲੀ ਦੇਣਯੋਗ ਤਾਰੀਖ਼ {date}",
  breakdown: "ਕੀ ਦੇਣਯੋਗ ਹੈ",
  fine: "ਜੁਰਮਾਨਾ",
  pay: "{amount} ਭੁਗਤਾਨ ਕਰੋ",
  payComing: "ਆਨਲਾਈਨ ਭੁਗਤਾਨ ਅਗਲੇ ਬਿਲਡ ਵਿੱਚ ਆਵੇਗਾ। ਤੁਸੀਂ ਸਕੂਲ ਦਫ਼ਤਰ ਜਾਂ TatvaOS ਵੈੱਬਸਾਈਟ ਉੱਤੇ ਭੁਗਤਾਨ ਕਰ ਸਕਦੇ ਹੋ।",
  securePayment: "ਸੁਰੱਖਿਅਤ ਭੁਗਤਾਨ · UPI, ਕਾਰਡ, ਨੈੱਟ ਬੈਂਕਿੰਗ",
  receipts: "ਰਸੀਦਾਂ",
  noReceipts: "ਅਜੇ ਕੋਈ ਰਸੀਦ ਨਹੀਂ।",
  paidOn: "{date} ਨੂੰ ਜਮ੍ਹਾਂ · {mode}",
  reverted: "ਸਕੂਲ ਵੱਲੋਂ ਰੱਦ",
  downloadReceipt: "ਰਸੀਦ ਡਾਊਨਲੋਡ ਕਰੋ",
  switchChild: "ਬੱਚਾ ਬਦਲੋ",
  switchChildSub: "ਹਰ ਬੱਚਾ ਆਪਣੇ ਸਕੂਲ ਲੌਗਇਨ ਨਾਲ ਸਾਈਨ ਇਨ ਰਹਿੰਦਾ ਹੈ।",
  open: "ਖੁੱਲ੍ਹਾ",
  addChild: "ਬੱਚਾ ਜੋੜੋ",
  addChildSub: "ਉਹੀ ਸਕੂਲ ਜਾਂ ਕੋਈ ਹੋਰ",
  alertsBoth: "ਹਰ ਬੱਚੇ ਦੀਆਂ ਸੂਚਨਾਵਾਂ ਹਮੇਸ਼ਾ ਆਉਂਦੀਆਂ ਹਨ, ਭਾਵੇਂ ਦੂਜਾ ਬੱਚਾ ਖੁੱਲ੍ਹਾ ਹੋਵੇ।",
  signOutOf: "{name} ਤੋਂ ਸਾਈਨ ਆਊਟ",
  homeworkTitle: "ਹੋਮਵਰਕ",
  noHomeworkYet: "ਅਜੇ ਕੋਈ ਹੋਮਵਰਕ ਨਹੀਂ।",
  attachmentsN: "{n} ਨੱਥੀ ਫ਼ਾਈਲਾਂ",
  attachmentOne: "1 ਨੱਥੀ ਫ਼ਾਈਲ",
  attachmentsTitle: "ਨੱਥੀ ਫ਼ਾਈਲਾਂ",
  openFile: "ਖੋਲ੍ਹੋ",
  fileOnWebsite: "ਹੁਣ ਇਹ ਫ਼ਾਈਲ TatvaOS ਵੈੱਬਸਾਈਟ ਉੱਤੇ ਖੋਲ੍ਹੋ।",
  byTeacher: "{name} ਵੱਲੋਂ",
  noticesTitle: "ਨੋਟਿਸ",
  noNotices: "ਅਜੇ ਕੋਈ ਨੋਟਿਸ ਨਹੀਂ।",
  pinned: "ਪਿੰਨ ਕੀਤਾ",
  important: "ਮਹੱਤਵਪੂਰਨ",
  calendarTitle: "ਕੈਲੰਡਰ",
  noEvents: "ਇਸ ਮਹੀਨੇ ਕੈਲੰਡਰ ਉੱਤੇ ਕੁਝ ਨਹੀਂ।",
  holidayLabel: "ਛੁੱਟੀ",
  eventLabel: "ਸਮਾਗਮ",
  inboxTitle: "ਸੂਚਨਾਵਾਂ",
  noInbox: "ਅਜੇ ਕੋਈ ਸੂਚਨਾ ਨਹੀਂ।",
  markAllRead: "ਸਭ ਨੂੰ ਪੜ੍ਹਿਆ ਕਰੋ",
  todayLabel: "ਅੱਜ",
  yesterdayLabel: "ਕੱਲ੍ਹ",
  profileTitle: "ਪ੍ਰੋਫ਼ਾਈਲ",
  admissionNo: "ਦਾਖ਼ਲਾ ਨੰਬਰ",
  classLabel: "ਜਮਾਤ",
  schoolLabel: "ਸਕੂਲ",
  usernameShort: "ਯੂਜ਼ਰਨੇਮ",
  languageLabel: "ਭਾਸ਼ਾ",
  changePassword: "ਪਾਸਵਰਡ ਬਦਲੋ",
  helpSupport: "ਸਹਾਇਤਾ",
  callSchool: "ਸਕੂਲ ਨੂੰ ਫ਼ੋਨ ਕਰੋ",
  emailSchool: "ਸਕੂਲ ਨੂੰ ਈਮੇਲ ਕਰੋ",
  appVersion: "ਐਪ ਸੰਸਕਰਣ {v}",
  currentPassword: "ਮੌਜੂਦਾ ਪਾਸਵਰਡ",
  newPassword: "ਨਵਾਂ ਪਾਸਵਰਡ",
  confirmPassword: "ਨਵਾਂ ਪਾਸਵਰਡ ਦੁਬਾਰਾ",
  passwordRule: "ਘੱਟੋ-ਘੱਟ 8 ਅੱਖਰ, ਜਿਨ੍ਹਾਂ ਵਿੱਚ ਵੱਡੇ ਅਤੇ ਛੋਟੇ ਅੱਖਰ, ਇੱਕ ਅੰਕ ਅਤੇ ਇੱਕ ਖ਼ਾਸ ਚਿੰਨ੍ਹ ਹੋਵੇ।",
  passwordsDiffer: "ਦੋਵੇਂ ਨਵੇਂ ਪਾਸਵਰਡ ਇੱਕੋ ਜਿਹੇ ਨਹੀਂ ਹਨ।",
  passwordWeak: "ਨਵਾਂ ਪਾਸਵਰਡ ਉੱਪਰ ਦਿੱਤੇ ਨਿਯਮ ਮੁਤਾਬਕ ਨਹੀਂ ਹੈ।",
  passwordChanged: "ਪਾਸਵਰਡ ਬਦਲ ਗਿਆ। ਨਵੇਂ ਪਾਸਵਰਡ ਨਾਲ ਦੁਬਾਰਾ ਸਾਈਨ ਇਨ ਕਰੋ।",
  save: "ਸੰਭਾਲੋ",
  mustChangeTitle: "ਆਪਣਾ ਪਾਸਵਰਡ ਬਣਾਓ",
  mustChangeBody: "ਸਕੂਲ ਨੇ ਤੁਹਾਨੂੰ ਅਸਥਾਈ ਪਾਸਵਰਡ ਦਿੱਤਾ ਹੈ। ਅੱਗੇ ਵਧਣ ਲਈ ਆਪਣਾ ਪਾਸਵਰਡ ਬਣਾਓ।",
  forgotTitle: "ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ",
  forgotSub: "ਅਸੀਂ ਇਸ ਲੌਗਇਨ ਲਈ ਸਕੂਲ ਕੋਲ ਦਰਜ ਮੋਬਾਈਲ ਨੰਬਰ ਜਾਂ ਈਮੇਲ ਉੱਤੇ ਇੱਕ ਕੋਡ ਭੇਜਾਂਗੇ।",
  sendCode: "ਕੋਡ ਭੇਜੋ",
  codeSentTo: "ਅਸੀਂ {to} ਉੱਤੇ ਕੋਡ ਭੇਜਿਆ ਹੈ। ਇਹ {m} ਮਿੰਟ ਚੱਲੇਗਾ।",
  otpLabel: "ਕੋਡ",
  verify: "ਜਾਂਚੋ",
  resendCode: "ਨਵਾਂ ਕੋਡ ਭੇਜੋ",
  setNewPassword: "ਨਵਾਂ ਪਾਸਵਰਡ ਬਣਾਓ",
  resetDone: "ਪਾਸਵਰਡ ਬਦਲ ਗਿਆ। ਹੁਣ ਤੁਸੀਂ ਸਾਈਨ ਇਨ ਕਰ ਸਕਦੇ ਹੋ।",
  backToSignIn: "ਸਾਈਨ ਇਨ ਉੱਤੇ ਵਾਪਸ",
  leaveTitle: "ਛੁੱਟੀ ਲਈ ਅਰਜ਼ੀ",
  leaveType: "ਛੁੱਟੀ ਦੀ ਕਿਸਮ",
  fromDate: "ਤੋਂ",
  toDate: "ਤੱਕ",
  reasonLabel: "ਕਾਰਨ",
  reasonPlaceholder: "ਜਿਵੇਂ ਬੁਖ਼ਾਰ, ਪਰਿਵਾਰਕ ਸਮਾਗਮ",
  submit: "ਜਮ੍ਹਾਂ ਕਰੋ",
  leaveSent: "ਛੁੱਟੀ ਦੀ ਅਰਜ਼ੀ ਭੇਜੀ ਗਈ। ਸਕੂਲ ਦਾ ਫ਼ੈਸਲਾ ਇੱਥੇ ਹੀ ਦਿਸੇਗਾ।",
  leaveDocNeeded: "{n} ਜਾਂ ਵੱਧ ਦਿਨਾਂ ਲਈ ਸਕੂਲ ਨੂੰ ਦਸਤਾਵੇਜ਼ ਚਾਹੀਦਾ ਹੈ। ਹੁਣ TatvaOS ਵੈੱਬਸਾਈਟ ਉੱਤੇ ਅਰਜ਼ੀ ਦਿਓ।",
  earlierDay: "ਪਿਛਲਾ ਦਿਨ",
  laterDay: "ਅਗਲਾ ਦਿਨ",
  fillAll: "ਕਿਰਪਾ ਕਰਕੇ ਸਾਰੇ ਖ਼ਾਨੇ ਭਰੋ।",
  noClassesDay: "ਇਸ ਦਿਨ ਕੋਈ ਜਮਾਤ ਨਹੀਂ।",
  freePeriod: "ਖ਼ਾਲੀ",
  changedToday: "ਅੱਜ ਬਦਲਿਆ ਗਿਆ",
  noReportCards: "ਅਜੇ ਕੋਈ ਰਿਪੋਰਟ ਕਾਰਡ ਨਹੀਂ। ਸਕੂਲ ਦੇ ਜਾਰੀ ਕਰਨ ਉੱਤੇ ਇੱਥੇ ਦਿਸਣਗੇ।",
  heldCard: "ਫ਼ੀਸ ਜਮ੍ਹਾਂ ਹੋਣ ਤੱਕ ਸਕੂਲ ਨੇ ਇਸਨੂੰ ਰੋਕਿਆ ਹੈ।",
  newLabel: "ਨਵਾਂ",
  openPdf: "PDF ਖੋਲ੍ਹੋ",
  publishedOn: "{date} ਨੂੰ ਜਾਰੀ",
  booksWithYou: "ਤੁਹਾਡੇ ਕੋਲ ਕਿਤਾਬਾਂ",
  overdueBooks: "ਮਿਆਦ ਲੰਘੀ",
  libraryRule: "ਤੁਸੀਂ {n} ਕਿਤਾਬਾਂ {d} ਦਿਨਾਂ ਲਈ ਲੈ ਸਕਦੇ ਹੋ।",
  noLoans: "ਹੁਣ ਤੁਹਾਡੇ ਕੋਲ ਲਾਇਬ੍ਰੇਰੀ ਦੀ ਕੋਈ ਕਿਤਾਬ ਨਹੀਂ।",
  libraryFine: "ਦੇਣਯੋਗ ਜੁਰਮਾਨਾ",
  notMember: "ਇਹ ਲੌਗਇਨ ਲਾਇਬ੍ਰੇਰੀ ਦਾ ਮੈਂਬਰ ਨਹੀਂ ਹੈ।",
  fileFailed: "ਫ਼ਾਈਲ ਨਹੀਂ ਖੁੱਲ੍ਹੀ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
  unlockPrompt: "TatvaOS School ਖੋਲ੍ਹੋ",
  unlockButton: "ਫ਼ਿੰਗਰਪ੍ਰਿੰਟ ਨਾਲ ਖੋਲ੍ਹੋ",
  usePassword: "ਇਸ ਦੀ ਥਾਂ ਪਾਸਵਰਡ ਨਾਲ",
  useFingerprint: "ਅਗਲੀ ਵਾਰ ਫ਼ਿੰਗਰਪ੍ਰਿੰਟ ਨਾਲ ਖੋਲ੍ਹਣਾ ਹੈ?",
  useFingerprintSub: "ਪਾਸਵਰਡ ਦੀ ਥਾਂ ਫ਼ਿੰਗਰਪ੍ਰਿੰਟ ਨਾਲ ਐਪ ਖੋਲ੍ਹੋ।",
  turnOn: "ਚਾਲੂ ਕਰੋ",
  notNow: "ਹੁਣ ਨਹੀਂ",
  fingerprintUnlock: "ਫ਼ਿੰਗਰਪ੍ਰਿੰਟ ਨਾਲ ਖੋਲ੍ਹਣਾ",
  onLabel: "ਚਾਲੂ",
  offLabel: "ਬੰਦ",
  sessionEnded: "{name} ਸਾਈਨ ਆਊਟ ਹੋ ਗਏ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਸਾਈਨ ਇਨ ਕਰੋ।",
  payTitle: "ਫ਼ੀਸ ਭੁਗਤਾਨ",
  payPreparing: "ਭੁਗਤਾਨ ਤਿਆਰ ਹੋ ਰਿਹਾ ਹੈ…",
  payTotalNote: "ਇਸ ਕੁੱਲ ਵਿੱਚ ਅੱਜ ਤੱਕ ਦਾ ਜੁਰਮਾਨਾ ਸ਼ਾਮਲ ਹੈ।",
  payWaiting: "ਭੁਗਤਾਨ ਦੀ ਪੁਸ਼ਟੀ ਦੀ ਉਡੀਕ…",
  payConfirming: "ਪੈਸਾ ਸਕੂਲ ਦੇ ਬੈਂਕ ਤੱਕ ਪਹੁੰਚ ਗਿਆ ਹੈ ਅਤੇ ਪੁਸ਼ਟੀ ਹੋ ਰਹੀ ਹੈ। ਦੁਬਾਰਾ ਭੁਗਤਾਨ ਨਾ ਕਰੋ।",
  paySuccess: "ਭੁਗਤਾਨ ਮਿਲ ਗਿਆ",
  paySuccessSub: "ਰਸੀਦ {no} ਤਿਆਰ ਹੈ।",
  payFailed: "ਭੁਗਤਾਨ ਪੂਰਾ ਨਹੀਂ ਹੋਇਆ।",
  payCancelled: "ਭੁਗਤਾਨ ਰੱਦ ਕੀਤਾ ਗਿਆ।",
  payStillWaiting: "ਅਜੇ ਵੀ ਬੈਂਕ ਦੀ ਉਡੀਕ ਹੈ। ਦੁਬਾਰਾ ਭੁਗਤਾਨ ਤੋਂ ਪਹਿਲਾਂ ਕੁਝ ਮਿੰਟ ਬਾਅਦ ਫ਼ੀਸ ਦੇਖੋ।",
  viewReceipt: "ਰਸੀਦ ਦੇਖੋ",
  doneLabel: "ਹੋ ਗਿਆ",
  hostelTitle: "ਹੋਸਟਲ",
  notInHostel: "ਹੁਣ ਤੁਹਾਡੇ ਕੋਲ ਹੋਸਟਲ ਦਾ ਕਮਰਾ ਨਹੀਂ ਹੈ।",
  roomLabel: "ਕਮਰਾ",
  floorLabel: "ਮੰਜ਼ਿਲ",
  bedLabel: "ਬਿਸਤਰਾ",
  blockLabel: "ਬਲਾਕ",
  wardensTitle: "ਵਾਰਡਨ",
  roommatesTitle: "ਕਮਰੇ ਦੇ ਸਾਥੀ",
  callLabel: "ਫ਼ੋਨ ਕਰੋ",
  acRoom: "AC ਕਮਰਾ",
  assignmentsTitle: "ਅਸਾਈਨਮੈਂਟ",
  noAssignments: "ਅਜੇ ਕੋਈ ਅਸਾਈਨਮੈਂਟ ਨਹੀਂ।",
  notSubmitted: "ਜਮ੍ਹਾਂ ਨਹੀਂ",
  submittedStatus: "ਜਮ੍ਹਾਂ ਕੀਤਾ",
  checkedStatus: "ਜਾਂਚਿਆ ਗਿਆ",
  returnedStatus: "ਦੁਬਾਰਾ ਕਰਨ ਲਈ ਵਾਪਸ",
  yourAnswer: "ਤੁਹਾਡਾ ਜਵਾਬ",
  answerPlaceholder: "ਆਪਣਾ ਜਵਾਬ ਲਿਖੋ",
  takePhoto: "ਫ਼ੋਟੋ ਲਓ",
  fromGallery: "ਗੈਲਰੀ ਤੋਂ",
  addPdf: "PDF",
  maxFiles: "ਵੱਧ ਤੋਂ ਵੱਧ 5 ਫ਼ਾਈਲਾਂ। ਭੇਜਣ ਤੋਂ ਪਹਿਲਾਂ ਫ਼ੋਟੋ ਛੋਟੀਆਂ ਕੀਤੀਆਂ ਜਾਂਦੀਆਂ ਹਨ।",
  submitAgain: "ਦੁਬਾਰਾ ਜਮ੍ਹਾਂ ਕਰੋ",
  submittedOk: "ਜਮ੍ਹਾਂ ਹੋ ਗਿਆ। ਤੁਹਾਡੇ ਅਧਿਆਪਕ ਹੁਣ ਇਸਨੂੰ ਦੇਖ ਸਕਦੇ ਹਨ।",
  closedLabel: "ਆਖ਼ਰੀ ਤਾਰੀਖ਼ ਲੰਘ ਗਈ ਹੈ, ਇਸ ਲਈ ਇਹ ਬੰਦ ਹੈ।",
  pdfTooBig: "PDF 10 MB ਤੋਂ ਵੱਡੀ ਹੈ।",
  removeFile: "ਹਟਾਓ",
  marksLabel: "ਅੰਕ",
  teacherRemark: "ਅਧਿਆਪਕ ਦੀ ਟਿੱਪਣੀ",
  answerNeeded: "ਜਵਾਬ ਲਿਖੋ ਜਾਂ ਫ਼ਾਈਲ ਜੋੜੋ।",
  seeAttached: "ਨੱਥੀ ਫ਼ਾਈਲਾਂ ਦੇਖੋ।",
  noteLabel: "ਨੋਟ ਦੀ ਫ਼ੋਟੋ (ਵਿਕਲਪਿਕ)",
  leaveDocRequired: "{n} ਜਾਂ ਵੱਧ ਦਿਨਾਂ ਲਈ ਸਕੂਲ ਨੂੰ ਦਸਤਾਵੇਜ਼ ਚਾਹੀਦਾ ਹੈ: ਉਸਦੀ ਫ਼ੋਟੋ ਜਾਂ PDF ਜੋੜੋ।",
  pdfTooBig5: "PDF 5 MB ਤੋਂ ਵੱਡੀ ਹੈ।",
  errorGeneric: "ਕੁਝ ਗ਼ਲਤ ਹੋ ਗਿਆ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
  months: "ਜਨਵਰੀ,ਫ਼ਰਵਰੀ,ਮਾਰਚ,ਅਪ੍ਰੈਲ,ਮਈ,ਜੂਨ,ਜੁਲਾਈ,ਅਗਸਤ,ਸਤੰਬਰ,ਅਕਤੂਬਰ,ਨਵੰਬਰ,ਦਸੰਬਰ",
  weekdaysShort: "ਐਤ,ਸੋਮ,ਮੰਗਲ,ਬੁੱਧ,ਵੀਰ,ਸ਼ੁੱਕਰ,ਸ਼ਨੀ",
  weekdays: "ਐਤਵਾਰ,ਸੋਮਵਾਰ,ਮੰਗਲਵਾਰ,ਬੁੱਧਵਾਰ,ਵੀਰਵਾਰ,ਸ਼ੁੱਕਰਵਾਰ,ਸ਼ਨੀਵਾਰ",
};

export const strings = { en, hi, bn, pa };
export type Lang = keyof typeof strings;
export const LANGS: Lang[] = ["en", "hi", "bn", "pa"];
