#!/usr/bin/env node
// Turns the TatvaOS School logo SVGs in assets/brand/svg (from the TatvaOS brand kit) into
// ui/brand.ts, so the app can draw them with react-native-svg. When the designer's master files
// arrive under the same names, copy them in and run:  node scripts/brand-svgs.js
const fs = require("fs");
const path = require("path");

const dir = path.join(__dirname, "../assets/brand/svg");
const out = path.join(__dirname, "../ui/brand.ts");
const files = fs.readdirSync(dir).filter((f) => f.endsWith(".svg")).sort();
const key = (f) => f.replace(/^tatvaos-school-/, "").replace(/\.svg$/, "").replace(/-(\w)/g, (_, c) => c.toUpperCase());

let ts = "// Generated by scripts/brand-svgs.js from assets/brand/svg (TatvaOS brand kit). Do not edit.\n";
ts += "// The wordmark is artwork: always draw these, never retype it in a font.\n\n";
ts += "export const brand = {\n";
for (const f of files) {
  const svg = fs.readFileSync(path.join(dir, f), "utf8").replace(/<\?xml[^>]*>/, "").replace(/<title>[^<]*<\/title>/, "").trim();
  const vb = /viewBox="([\d.\s-]+)"/.exec(svg);
  const [, , w, h] = (vb ? vb[1] : "0 0 1 1").split(/\s+/).map(Number);
  ts += `  ${key(f)}: { ratio: ${(w / h).toFixed(4)}, xml: ${JSON.stringify(svg)} },\n`;
}
ts += "} as const;\n\nexport type BrandLogo = keyof typeof brand;\n";
fs.writeFileSync(out, ts);
console.log(`wrote ui/brand.ts: ${files.map(key).join(", ")}`);
