/**
 * Lets the Android RELEASE build compile on Windows, whose paths stop at 260
 * characters.
 *
 * ── WHAT BROKE, 16 SEPTEMBER 2026 ─────────────────────────────────────────
 *  The first arm64 release build since react-native-safe-area-context joined
 *  the app (fb61236, 11 Sept) died in ninja:
 *
 *    Stat(safeareacontext_autolinked_build/CMakeFiles/
 *         react_codegen_safeareacontext.dir/C_/Users/amitd/.../node_modules/
 *         react-native-safe-area-context/common/cpp/react/renderer/components/
 *         safeareacontext/RNCSafeAreaViewShadowNode.cpp.o):
 *         Filename longer than 260 characters
 *
 *  CMake names an object built from a source OUTSIDE the project after that
 *  source's full absolute path. That object path was 263 characters on its
 *  own, 378 with the build directory — so no amount of shortening the project
 *  folder alone could fit it. The build installed on the Samsung was made 25
 *  minutes before the module landed, which is why nothing failed until now.
 *
 * ── WHAT THIS DOES ───────────────────────────────────────────────────────
 *  CMake replaces an over-long object name with a short hash — but only when
 *  the path exceeds CMAKE_OBJECT_PATH_MAX, and when cross-compiling FOR
 *  ANDROID the default is 1000, not Windows' 250. So it never triggered. This
 *  sets it to 240: long enough that the object DIRECTORY fits beneath it (a
 *  limit below the directory length makes CMake give up — 128 was tried and
 *  printed "cannot be safely placed" for exactly that reason), short enough
 *  that directory + hash + file name stays under Windows' 260.
 *
 *  It is NOT sufficient from a deep folder: the object directory itself grows
 *  with the checkout's path. Measured working from C:\Users\amitd\tvb. From
 *  C:\Users\amitd\Downloads\tatvaos-one\tatvaos-mobile the directory is 195
 *  characters and the hashed path still does not fit. See WELCOME §3 trap 10.
 *
 * ── WHY A PLUGIN AND NOT AN EDIT ─────────────────────────────────────────
 *  android/ is generated by `expo prebuild` and is not committed. An edit to
 *  android/app/build.gradle is erased by the next prebuild without a word, and
 *  the next build fails with the same 260-character error and no memory of
 *  having been fixed. This re-applies it every time.
 *
 *  If Expo's template stops having a `defaultConfig {` block, this THROWS
 *  rather than returning quietly: a prebuild that silently drops the fix is the
 *  failure this file exists to prevent.
 */

const { withAppBuildGradle } = require('expo/config-plugins');

const FLAG = '-DCMAKE_OBJECT_PATH_MAX=';

module.exports = function withShortNativeObjectPaths(config, { max = 240 } = {}) {
  return withAppBuildGradle(config, (cfg) => {
    const src = cfg.modResults.contents;

    // Idempotent: prebuild without --clean edits the existing file in place.
    if (src.includes(FLAG)) return cfg;

    const anchor = /defaultConfig\s*\{/;
    if (!anchor.test(src)) {
      throw new Error(
        'withShortNativeObjectPaths: android/app/build.gradle has no `defaultConfig {` block. '
        + 'The Expo template has changed and the Windows long-path fix was NOT applied — '
        + 'the Android release build will fail with "Filename longer than 260 characters".',
      );
    }

    cfg.modResults.contents = src.replace(anchor, (m) => `${m}
        // Added by plugins/withShortNativeObjectPaths.js — Windows 260-char limit.
        externalNativeBuild {
            cmake {
                arguments "${FLAG}${max}"
            }
        }`);
    return cfg;
  });
};
